class GameLocalization {
  static const List<String> supportedLanguages = ['tr', 'en', 'es', 'de'];

  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'game_title': 'HexRush Kağanlığı',
      'food': 'Gıda',
      'wood': 'Odun',
      'flour': 'Un',
      'plank': 'Kereste',
      'bread': 'Ekmek',
      'furniture': 'Mobilya',
      'stone': 'Taş',
      'iron': 'Demir',
      'crowns': 'Kut / Şan',
      'land': 'Toprak',
      'spring': 'Bahar',
      'summer': 'Yaz',
      'autumn': 'Sonbahar',
      'winter': 'Kış',
      'season_spring': 'Bahar Geldi',
      'season_summer': 'Yaz Sıcağı Başladı',
      'season_autumn': 'Güz Hasadı Başladı',
      'season_winter': 'Kış Ayazı Bastırdı',
      'zud_blizzard_alert': 'DİKKAT: Şiddetli Zud Afeti!',
      'spring_bonus_desc': 'Sürüler coşuyor, bereket ve taze filizler',
      'summer_bonus_desc': 'Gıda ve ekmek üretimi zirvede',
      'autumn_bonus_desc': 'Odun ve kereste verimi +%25, hasat vakti',
      'winter_penalty_desc': 'Don ve ayaz: Gıda üretimi %50 yavaşlar',
      'zud_production_penalty': 'Kritik don: Tüm üretimler -%40 yavaşlar!',
      'year': 'Yıl',
      'conquer': 'Toprağı Fethet',
      'cost': 'Maliyet',
      'free': 'ÜCRETSİZ',
      'build': 'İnşa Et',
      'upgrade': 'Geliştir',
      'collect': 'Topla',
      'level': 'Seviye',
      'per_sec': '/sn',
      'frenzy_boost': '10x Toy Coşkusu',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'sound': 'Ses',
      'mute': 'Sessize Al',
      'reset_game': 'Oyunu Sıfırla',
      'castle_title': 'Kağan Otağı',
      'castle_desc': 'Kağanlığın kalbi. Otağ büyüdükçe töreler ve yeni yapılar açılır.',
      'global_bonus': 'Küresel Hız Bonusu',
      'next_unlock': 'Sonraki Kilit Açılımı',
      'biome_meadow': 'Çayır',
      'biome_forest': 'Orman',
      'biome_mountain': 'Dağ',
      'biome_sea': 'Deniz',
      'biome_desert': 'Karakum Çölü',
      'biome_tundra': 'Altay Tundrası',
      'biome_volcano': 'Yanardağ',
      'biome_wetland': 'Bozkır Sazlığı',
      'biome_celestial_crater': 'Göksel Krater',
      'biome_celestialCrater': 'Göksel Krater',
      'biome_kurgan_valley': 'Atalar Kurganı',
      'biome_kurganValley': 'Atalar Kurganı',
      'biome_crystal_chasm': 'Kristal Yarığı',
      'biome_crystalChasm': 'Kristal Yarığı',
      'corn_name': 'Buğday Tarlası',
      'corn_desc': 'Temel buğday ve erzak üretimi yapar.',
      'barley_name': 'Arpa & Darı Tarlası',
      'barley_desc': 'Soğuğa dayanıklı bozkır tahılı; kış ayazında da üretir.',
      'pasture_name': 'Bozkır Otlağı & Hara',
      'pasture_desc': 'Bozkır atları ve sürü otlağı; yüksek iaşe ve et üretir.',
      'orchard_name': 'Yemişlik Bahçesi',
      'orchard_desc': 'Yaz ve sonbaharda coşan dağ meyveleri bahçesi.',
      'quarry_name': 'Taş Yonma Ocağı',
      'quarry_desc': 'Otağ ve sur inşası için saf taş kütleleri çıkarır.',
      'resin_camp_name': 'Katran & Huş Otağı',
      'resin_camp_desc': 'Yurt yalıtımı ve otağ direkleri için kaliteli huş odunu üretir.',
      'lumberjack_name': 'Hızar & Oduncu Otağı',
      'lumberjack_desc': 'Temel odun üretimi yapar.',
      'windmill_name': 'Yel Değirmeni',
      'windmill_desc': 'Gıdayı Un\'a çevirir.',
      'sawmill_name': 'Hızar Otağı',
      'sawmill_desc': 'Odunu Kalas\'a çevirir.',
      'bakery_name': 'Taş Köz Fırını',
      'bakery_desc': 'Un ve Gıdadan Ekmek üretir.',
      'furniture_name': 'Marangoz Otağı',
      'furniture_desc': 'Kalas ve Odundan Mobilya üretir.',
      'worker_name': 'İşçi Kulübesi',
      'worker_desc': 'Otomatik hammadde taşır.',
      'watchtower_name': 'Gözcü Kulesi',
      'watchtower_desc': 'Geniş görüş alanı açar.',
      'mine_name': 'Maden Ocağı',
      'mine_desc': 'Taş ve demir çıkarır.',
      'bridge_name': 'Ahşap Köprü',
      'bridge_desc': 'Deniz geçişini sağlar.',
      'fisherman_name': 'Balıkçı',
      'fisherman_desc': 'Su üzerinden gıda üretimi yapar.',
      'fisherman_hut_name': 'Balıkçı Barınağı',
      'fisherman_hut_desc': 'Balıkçılar için toplama noktasıdır.',
      // Özel Çöl Binaları
      'oasis_cistern_name': 'Vaha Sarnıcı',
      'oasis_cistern_desc': 'Çöl kuraklığını siler, etrafa +%40 verim aurası yayar.',
      'caravanserai_name': 'İpek Yolu Kervansarayı',
      'caravanserai_desc': 'Kervan ticaretiyle ekmek ve erzak kazandırır.',
      'astrolabe_name': 'Gök Gözlemevi',
      'astrolabe_desc': 'Çöl gecelerinde yıldızları haritalar.',
      // Özel Tundra Binaları
      'reindeer_sanctuary_name': 'Geyik Otağı',
      'reindeer_sanctuary_desc': 'Dondurucu ayaza dirençli gıda üretir.',
      'geothermal_bath_name': 'Jeotermal Kaplıca',
      'geothermal_bath_desc': 'Sıcak mineral buharıyla işçi hızını 2x yapar.',
      'permafrost_dig_name': 'Kehribar Sondajı',
      'permafrost_dig_desc': 'Donmuş topraktan mamut fosili ve demir çıkarır.',
      // Özel Volkan Binaları
      'steam_vent_name': 'Buhar Bacası',
      'steam_vent_desc': 'Jeotermal buhar basıncıyla enerji ve taş üretir.',
      'obsidian_forge_name': 'Obsidyen Dökümhanesi',
      'obsidian_forge_desc': 'Obsidyen aletlerle demir ve taş işler.',
      // Özel Sazlık Binaları
      'herbalist_yurt_name': 'Şifacı Otağı',
      'herbalist_yurt_desc': 'Sazlık nilüferlerinden şifalı gıda üretir.',
      'scribe_workshop_name': 'Yazıt Atölyesi',
      'scribe_workshop_desc': 'Kamışlardan antik parşömen ve kalas üretir.',
      // Efsanevi Binalar
      'celestial_anvil_name': 'Gök Demircisi',
      'celestial_anvil_desc': 'Göktaşından nadir Gök Demiri ve çelik döver.',
      'ancestral_totem_name': 'Kurgan Koruyucusu',
      'ancestral_totem_desc': 'Tüm geçmiş göçlerin kümülatif bereketiyle üretimi katlar.',
      'prismatic_resonator_name': 'Rezonans Kulesi',
      'prismatic_resonator_desc': 'Tüm kutlu tapınakların gücünü ikiye katlar.',
      // Yeni Mekanik Binaları
      'granary_vault_name': 'Kurgan Mahzeni',
      'granary_vault_desc': '3 hex menzildeki binaların taşıma ve hasat hızını +%50 artırır.',
      'kumis_yurt_name': 'Kımız Otağı',
      'kumis_yurt_desc': 'At sütü fermente eden otağ; değerli göçebe kımız içeceği üretir.',
      'felt_tent_workshop_name': 'Keçe Çadırhanesi',
      'felt_tent_workshop_desc': 'Yün işleyip çadırlar ve ticaret için dayanıklı keçe üretir.',
      'damascus_forge_name': 'Şam Çeliği Dökümhanesi',
      'damascus_forge_desc': 'Kat kat dövme çelik ocağı; yüksek nitelikli Şam Çeliği üretir.',
      'runic_stele_name': 'Orhun Bitig Taşı',
      'runic_stele_desc': 'Töre Bilgelik Ağacı için kadim bozkır yazıtı ve bilgelik üretir.',
      'market_title': 'Bozkır Kurultay Pazarı',
      'market_desc': 'Ürettiğin malları takasla taş, demir ve hanlık şanına dönüştür.',
      'trade': 'Takas Et',
      'tore_title': 'Töre & Kurultay',
      'tore_desc': 'Kadim töre yetenekleri ve unvanlarla kağanlığını güçlendir.',
      'learn_talent': 'Öğren',
      'claim_title': 'Unvanı Al',
      'warm_tile': 'Isıt (+%50 Hız)',
      'locked_castle_lvl': 'Otağ Seviye {0} Gerekli',
      'logistics_capacity': 'Taşıma Kapasitesi',
      'logistics_utilized': 'Kullanılan',
      'logistics_idle': 'Boşta',
      'logistics_load': 'Lojistik Yükü',
      'capacity': 'Kapasite',
      'in_coverage_buildings': '{0} Üretim Yapısı Menzilde',
      'resource_breakdown_title': 'Üretim & Tüketim Dökümü',
      'total_production': 'Toplam Üretim',
      'total_consumption': 'Toplam Tüketim',
      'net_total_label': 'Net Bilanço',
      'producers_label': 'ÜRETİCİLER',
      'consumers_label': 'TÜKETİCİLER',
      'no_active_buildings': 'Bu kaynak için aktif üretim veya tüketim yapan bina yok.',
      'hexpedia_title': 'HEXPEDIA - BOZKIR ANSİKLOPEDİSİ',
      'hexpedia_search_hint': 'Mekanik, bina veya biyom ara...',
      'hexpedia_stats': 'MEKANİK VERİLERİ & FORMÜLLER',
      'hexpedia_step_guide': 'ADIM ADIM UYGULAMA REHBERİ',
      'hexpedia_tips': 'TAKTİKSEL BOZKIR İPUÇLARI',
      'hexpedia_empty': 'Arama kriterine uygun mekanik veya rehber bulunamadı.',
    },
    'en': {
      'game_title': 'HexRush Khaganate',
      'food': 'Food',
      'wood': 'Wood',
      'flour': 'Flour',
      'plank': 'Plank',
      'bread': 'Bread',
      'furniture': 'Furniture',
      'stone': 'Stone',
      'iron': 'Iron',
      'crowns': 'Glory / Renown',
      'land': 'Land',
      'spring': 'Spring',
      'summer': 'Summer',
      'autumn': 'Autumn',
      'winter': 'Winter',
      'season_spring': 'Spring Has Arrived',
      'season_summer': 'Summer Has Begun',
      'season_autumn': 'Autumn Harvest Has Begun',
      'season_winter': 'Winter Frost Has Fallen',
      'zud_blizzard_alert': 'WARNING: Severe Zud Blizzard!',
      'spring_bonus_desc': 'Herds thrive, pasture fertility surges',
      'summer_bonus_desc': 'Food and grain production at peak',
      'autumn_bonus_desc': 'Wood and lumber yield +25%, harvest time',
      'winter_penalty_desc': 'Frost and cold: Food yields reduced by 50%',
      'zud_production_penalty': 'Critical blizzard: All production reduced by 40%!',
      'year': 'Year',
      'conquer': 'Conquer Land',
      'cost': 'Cost',
      'free': 'FREE',
      'build': 'Build',
      'upgrade': 'Upgrade',
      'collect': 'Collect',
      'level': 'Level',
      'per_sec': '/s',
      'frenzy_boost': '10x Steppe Surge',
      'settings': 'Settings',
      'language': 'Language',
      'sound': 'Sound',
      'mute': 'Mute',
      'reset_game': 'Reset Game',
      'castle_title': 'Khan\'s Yurt',
      'castle_desc': 'The heart of your steppe realm. Expands traditions and unlocks new structures.',
      'global_bonus': 'Global Speed Bonus',
      'next_unlock': 'Next Unlock',
      'biome_meadow': 'Meadow',
      'biome_forest': 'Forest',
      'biome_mountain': 'Mountain',
      'biome_sea': 'Sea',
      'biome_desert': 'Desert',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Volcano',
      'biome_wetland': 'Wetlands',
      'biome_celestial_crater': 'Celestial Crater',
      'biome_celestialCrater': 'Celestial Crater',
      'biome_kurgan_valley': 'Ancestral Kurgan',
      'biome_kurganValley': 'Ancestral Kurgan',
      'biome_crystal_chasm': 'Crystal Chasm',
      'biome_crystalChasm': 'Crystal Chasm',
      'corn_name': 'Wheat Field',
      'corn_desc': 'Produces staple wheat and provisions.',
      'barley_name': 'Barley Field',
      'barley_desc': 'Frost-resilient steppe grain that yields in cold weather.',
      'pasture_name': 'Steppe Pasture',
      'pasture_desc': 'Grazing herds and steppe horses; high food and meat yield.',
      'orchard_name': 'Steppe Orchard',
      'orchard_desc': 'Wild fruits that surge in summer and autumn.',
      'quarry_name': 'Stone Quarry',
      'quarry_desc': 'Excavates pure stone blocks for khaganate construction.',
      'resin_camp_name': 'Birch & Resin Camp',
      'resin_camp_desc': 'Harvests high quality birch timber and yurt insulation.',
      'lumberjack_name': 'Lumberjack Lodge',
      'lumberjack_desc': 'Produces timber.',
      'windmill_name': 'Windmill',
      'windmill_desc': 'Converts Food into Flour.',
      'sawmill_name': 'Timber Mill',
      'sawmill_desc': 'Converts Wood into Planks.',
      'bakery_name': 'Stone Hearth Bakery',
      'bakery_desc': 'Produces Bread from Flour & Food.',
      'furniture_name': 'Carpenter Lodge',
      'furniture_desc': 'Produces Furniture from Planks.',
      'worker_name': 'Worker Hut',
      'worker_desc': 'Automates resource collection.',
      'watchtower_name': 'Watchtower',
      'watchtower_desc': 'Reveals fog of war.',
      'mine_name': 'Mine Quarry',
      'mine_desc': 'Produces Stone and Iron.',
      'bridge_name': 'Wooden Bridge',
      'bridge_desc': 'Allows crossing water tiles.',
      'fisherman_name': 'Fisherman',
      'fisherman_desc': 'Produces food from water tiles.',
      'fisherman_hut_name': 'Fisherman Hut',
      'fisherman_hut_desc': 'Collection point for fishermen.',
      // Desert
      'oasis_cistern_name': 'Oasis Cistern',
      'oasis_cistern_desc': 'Clears drought and gives +40% fertility aura.',
      'caravanserai_name': 'Silk Road Caravanserai',
      'caravanserai_desc': 'Trades goods for bread and wealth.',
      'astrolabe_name': 'Desert Astrolabe',
      'astrolabe_desc': 'Maps desert stars for celestial guidance.',
      // Tundra
      'reindeer_sanctuary_name': 'Reindeer Sanctuary',
      'reindeer_sanctuary_desc': 'Produces frost-resilient food and warmth.',
      'geothermal_bath_name': 'Geothermal Bath',
      'geothermal_bath_desc': 'Doubles worker speed with warm spring steam.',
      'permafrost_dig_name': 'Permafrost Dig',
      'permafrost_dig_desc': 'Excavates mammoth fossils and iron ore.',
      // Volcano
      'steam_vent_name': 'Steam Vent Dynamo',
      'steam_vent_desc': 'Generates steam pressure and stone.',
      'obsidian_forge_name': 'Obsidian Master Forge',
      'obsidian_forge_desc': 'Forges obsidian-hardened tools and iron.',
      // Wetland
      'herbalist_yurt_name': 'Herbalist Yurt',
      'herbalist_yurt_desc': 'Brews nourishing remedies from wetland flora.',
      'scribe_workshop_name': 'Reed Scribe Workshop',
      'scribe_workshop_desc': 'Crafts ancient scrolls and planks.',
      // Legendary
      'celestial_anvil_name': 'Celestial Anvil',
      'celestial_anvil_desc': 'Forges rare Meteoric Steel from fallen meteorites.',
      'ancestral_totem_name': 'Ancestral Totem',
      'ancestral_totem_desc': 'Channels cumulative migration heritage.',
      'prismatic_resonator_name': 'Prismatic Resonator',
      'prismatic_resonator_desc': 'Doubles the power of all sacred shrines.',
      // New Mechanic Buildings
      'granary_vault_name': 'Kurgan Vault',
      'granary_vault_desc': 'Logistics storehouse boosting collection speed of nearby buildings within 3 hexes by +50%.',
      'kumis_yurt_name': 'Kumis Yurt',
      'kumis_yurt_desc': 'Ferments mare milk to brew traditional steppe kumis.',
      'felt_tent_workshop_name': 'Felt Tent Workshop',
      'felt_tent_workshop_desc': 'Processes raw wool into sturdy felt for yurts and commerce.',
      'damascus_forge_name': 'Damascus Master Forge',
      'damascus_forge_desc': 'Forges Damascus steel ingots through layered metallurgy.',
      'runic_stele_name': 'Orkhon Runic Stele',
      'runic_stele_desc': 'Inscribes ancient steppe knowledge to generate Lore for the Töre tree.',
      'market_title': 'Steppe Bazaar',
      'market_desc': 'Trade goods for stone, iron, and glory.',
      'trade': 'Trade',
      'tore_title': 'Töre & Council',
      'tore_desc': 'Empower your realm with ancient traditions and titles.',
      'learn_talent': 'Learn',
      'claim_title': 'Claim Title',
      'warm_tile': 'Warm (+50% Speed)',
      'locked_castle_lvl': 'Requires Yurt Lv.{0}',
      'logistics_capacity': 'Hauling Capacity',
      'logistics_utilized': 'Utilized',
      'logistics_idle': 'Idle',
      'logistics_load': 'Logistics Load',
      'capacity': 'Capacity',
      'in_coverage_buildings': '{0} Production Buildings in Range',
      'resource_breakdown_title': 'Production & Consumption Breakdown',
      'total_production': 'Total Production',
      'total_consumption': 'Total Consumption',
      'net_total_label': 'Net Balance',
      'producers_label': 'PRODUCERS',
      'consumers_label': 'CONSUMERS',
      'no_active_buildings': 'No active buildings producing or consuming this resource.',
      'hexpedia_title': 'HEXPEDIA - STEPPE ENCYCLOPEDIA',
      'hexpedia_search_hint': 'Search mechanics, buildings or biomes...',
      'hexpedia_stats': 'MECHANIC STATS & FORMULAS',
      'hexpedia_step_guide': 'STEP-BY-STEP GUIDE',
      'hexpedia_tips': 'TACTICAL STEPPE TIPS',
      'hexpedia_empty': 'No matching mechanics or guides found.',
    },
    'es': {
      'game_title': 'Kaganato HexRush',
      'food': 'Comida',
      'wood': 'Madera',
      'flour': 'Harina',
      'plank': 'Tablón',
      'bread': 'Pan',
      'furniture': 'Muebles',
      'stone': 'Piedra',
      'iron': 'Hierro',
      'crowns': 'Gloria / Rango',
      'land': 'Tierra',
      'spring': 'Primavera',
      'summer': 'Verano',
      'autumn': 'Otoño',
      'winter': 'Invierno',
      'season_spring': 'La Primavera Ha Llegado',
      'season_summer': 'El Verano Ha Comenzado',
      'season_autumn': 'Ha Comenzado la Cosecha de Otoño',
      'season_winter': 'Ha Llegado el Frío Invierno',
      'zud_blizzard_alert': '¡ATENCIÓN: Tormenta de Zud!',
      'spring_bonus_desc': 'Los rebaños prosperan y brotan los pastos',
      'summer_bonus_desc': 'Producción de comida y trigo al máximo',
      'autumn_bonus_desc': 'Rendimiento de madera +25%, tiempo de cosecha',
      'winter_penalty_desc': 'Helada y frío: Producción de comida reducida al 50%',
      'zud_production_penalty': 'Tormenta crítica: ¡Toda la producción reducida en un 40%!',
      'year': 'Año',
      'conquer': 'Conquistar',
      'cost': 'Coste',
      'free': 'GRATIS',
      'build': 'Construir',
      'upgrade': 'Mejorar',
      'collect': 'Recoger',
      'level': 'Nivel',
      'per_sec': '/s',
      'frenzy_boost': '10x Frenesí de Estepa',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'sound': 'Sonido',
      'mute': 'Silenciar',
      'reset_game': 'Reiniciar Juego',
      'castle_title': 'Yurta del Kan',
      'castle_desc': 'El corazón de tu estepa. Desbloquea tradiciones y nuevos edificios.',
      'global_bonus': 'Bonus de Velocidad Global',
      'next_unlock': 'Próximo Desbloqueo',
      'biome_meadow': 'Prado',
      'biome_forest': 'Bosque',
      'biome_mountain': 'Montaña',
      'biome_sea': 'Mar',
      'biome_desert': 'Desierto',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Volcán',
      'biome_wetland': 'Humedal',
      'biome_celestial_crater': 'Cráter Celestial',
      'biome_celestialCrater': 'Cráter Celestial',
      'biome_kurgan_valley': 'Kurgan Ancestral',
      'biome_kurganValley': 'Kurgan Ancestral',
      'biome_crystal_chasm': 'Abismo de Cristal',
      'biome_crystalChasm': 'Abismo de Cristal',
      'corn_name': 'Campo de Trigo',
      'corn_desc': 'Produce trigo y provisiones básicas.',
      'barley_name': 'Campo de Cebada',
      'barley_desc': 'Cereal resistente al frío.',
      'pasture_name': 'Pasto de Estepa',
      'pasture_desc': 'Rebaños y caballos de estepa; alta producción de carne.',
      'orchard_name': 'Huerto de Frutas',
      'orchard_desc': 'Frutas silvestres que prosperan en verano y otoño.',
      'quarry_name': 'Cantera de Piedra',
      'quarry_desc': 'Extrae bloques de piedra para la construcción.',
      'resin_camp_name': 'Campamento de Resina',
      'resin_camp_desc': 'Madera de abedul y resina para yurtas.',
      'lumberjack_name': 'Cabaña de Leñador',
      'lumberjack_desc': 'Produce madera.',
      'windmill_name': 'Molino de Viento',
      'windmill_desc': 'Convierte Comida en Harina.',
      'sawmill_name': 'Aserradero',
      'sawmill_desc': 'Convierte Madera en Tablones.',
      'bakery_name': 'Horno de Piedra',
      'bakery_desc': 'Produce Pan.',
      'furniture_name': 'Taller de Carpintería',
      'furniture_desc': 'Produce Muebles.',
      'worker_name': 'Cabaña de Obreros',
      'worker_desc': 'Transporta recursos automáticamente.',
      'watchtower_name': 'Torre de Guardia',
      'watchtower_desc': 'Despeja la niebla.',
      'mine_name': 'Mina',
      'mine_desc': 'Extrae Piedra y Hierro.',
      'bridge_name': 'Puente de Madera',
      'bridge_desc': 'Permite cruzar el mar.',
      'fisherman_name': 'Pescador',
      'fisherman_desc': 'Produce comida en el agua.',
      'fisherman_hut_name': 'Cabaña de Pesca',
      'fisherman_hut_desc': 'Punto de recogida para pescadores.',
      // Desert
      'oasis_cistern_name': 'Cisterna de Oasis',
      'oasis_cistern_desc': 'Elimina la sequía y brinda un aura de +40%.',
      'caravanserai_name': 'Caravasar de la Ruta de la Seda',
      'caravanserai_desc': 'Comercia bienes por pan y provisiones.',
      'astrolabe_name': 'Astrolabio del Desierto',
      'astrolabe_desc': 'Mapea las estrellas del desierto.',
      // Tundra
      'reindeer_sanctuary_name': 'Santuario de Renos',
      'reindeer_sanctuary_desc': 'Produce comida y calor resistentes al frío.',
      'geothermal_bath_name': 'Baño Geotérmico',
      'geothermal_bath_desc': 'Duplica la velocidad de los obreros.',
      'permafrost_dig_name': 'Excavación Permafrost',
      'permafrost_dig_desc': 'Extrae fósiles de mamut y mineral de hierro.',
      // Volcano
      'steam_vent_name': 'Ventila de Vapor',
      'steam_vent_desc': 'Genera presión de vapor y piedra.',
      'obsidian_forge_name': 'Forja de Obsidiana',
      'obsidian_forge_desc': 'Forja herramientas de obsidiana y hierro.',
      // Wetland
      'herbalist_yurt_name': 'Yurta del Herbolario',
      'herbalist_yurt_desc': 'Elabora alimentos curativos del humedal.',
      'scribe_workshop_name': 'Taller de Escribas',
      'scribe_workshop_desc': 'Elabora pergaminos antiguos y tablones.',
      // Legendary
      'celestial_anvil_name': 'Yunque Celestial',
      'celestial_anvil_desc': 'Forja Acero Meteórico a partir de meteoritos.',
      'ancestral_totem_name': 'Tótem Ancestral',
      'ancestral_totem_desc': 'Canaliza el poder de todas las migraciones.',
      'prismatic_resonator_name': 'Resonador Prismático',
      'prismatic_resonator_desc': 'Duplica el poder de todos los santuarios sagrados.',
      // New Mechanic Buildings
      'granary_vault_name': 'Bóveda de Kurgan',
      'granary_vault_desc': 'Almacén logístico que aumenta la velocidad de recolección en 3 hexágonos un +50%.',
      'kumis_yurt_name': 'Yurta de Kumis',
      'kumis_yurt_desc': 'Fermenta leche de yegua para producir kumis tradicional.',
      'felt_tent_workshop_name': 'Taller de Fieltro',
      'felt_tent_workshop_desc': 'Procesa lana en fieltro resistente para yurtas y comercio.',
      'damascus_forge_name': 'Forja de Damasco',
      'damascus_forge_desc': 'Forja acero de Damasco de alta calidad mediante capas.',
      'runic_stele_name': 'Estela Rúnica de Orjón',
      'runic_stele_desc': 'Inscribe conocimientos ancestrales y genera sabiduría para el árbol Töre.',
      'market_title': 'Bazar de la Estepa',
      'market_desc': 'Comercia bienes por piedra, hierro y gloria.',
      'trade': 'Comerciar',
      'tore_title': 'Töre y Consejo',
      'tore_desc': 'Fortalece tu reino con tradiciones ancestrales.',
      'learn_talent': 'Aprender',
      'claim_title': 'Reclamar Título',
      'warm_tile': 'Calentar (+50%)',
      'locked_castle_lvl': 'Requiere Yurta Nivel {0}',
      'logistics_capacity': 'Capacidad de Carga',
      'logistics_utilized': 'En Uso',
      'logistics_idle': 'Inactivo',
      'logistics_load': 'Carga Logística',
      'capacity': 'Capacidad',
      'in_coverage_buildings': '{0} Edificios Productivos en Rango',
      'resource_breakdown_title': 'Desglose de Producción y Consumo',
      'total_production': 'Producción Total',
      'total_consumption': 'Consumo Total',
      'net_total_label': 'Balance Neto',
      'producers_label': 'PRODUCTORES',
      'consumers_label': 'CONSUMIDORES',
      'no_active_buildings': 'No hay edificios activos produciendo o consumiendo este recurso.',
      'hexpedia_title': 'HEXPEDIA - ENCICLOPEDIA DE LA ESTEPA',
      'hexpedia_search_hint': 'Buscar mecánicas, edificios o biomas...',
      'hexpedia_stats': 'ESTADÍSTICAS Y FÓRMULAS',
      'hexpedia_step_guide': 'GUÍA PASO A PASO',
      'hexpedia_tips': 'CONSEJOS TÁCTICOS',
      'hexpedia_empty': 'No se encontraron mecánicas coincidentes.',
    },
    'de': {
      'game_title': 'HexRush Khaganat',
      'food': 'Nahrung',
      'wood': 'Holz',
      'flour': 'Mehl',
      'plank': 'Bretter',
      'bread': 'Brot',
      'furniture': 'Möbel',
      'stone': 'Stein',
      'iron': 'Eisen',
      'crowns': 'Ruhm / Ehre',
      'land': 'Land',
      'spring': 'Frühling',
      'summer': 'Sommer',
      'autumn': 'Herbst',
      'winter': 'Winter',
      'season_spring': 'Der Frühling Ist Da',
      'season_summer': 'Der Sommer Hat Begonnen',
      'season_autumn': 'Die Herbsternte Hat Begonnen',
      'season_winter': 'Der Winterfrost Ist Hereingebrochen',
      'zud_blizzard_alert': 'ACHTUNG: Schwerer Zud-Schneesturm!',
      'spring_bonus_desc': 'Die Herden gedeihen, die Weiden sprießen',
      'summer_bonus_desc': 'Nahrungs- und Getreideproduktion auf dem Höhepunkt',
      'autumn_bonus_desc': 'Holz- und Bauholzertrag +25%, Erntezeit',
      'winter_penalty_desc': 'Frost und Kälte: Nahrungsproduktion um 50% verlangsamt',
      'zud_production_penalty': 'Kritischer Schneesturm: Gesamte Produktion um 40% verlangsamt!',
      'year': 'Jahr',
      'conquer': 'Erobern',
      'cost': 'Kosten',
      'free': 'KOSTENLOS',
      'build': 'Bauen',
      'upgrade': 'Aufwerten',
      'collect': 'Sammeln',
      'level': 'Stufe',
      'per_sec': '/s',
      'frenzy_boost': '10x Steppendrang',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'sound': 'Ton',
      'mute': 'Stumm',
      'reset_game': 'Spiel zurücksetzen',
      'castle_title': 'Khans-Jurte',
      'castle_desc': 'Das Herz deines Steppenreiches. Schaltet Traditionen und neue Bauten frei.',
      'global_bonus': 'Globaler Geschwindigkeitsbonus',
      'next_unlock': 'Nächste Freischaltung',
      'biome_meadow': 'Wiese',
      'biome_forest': 'Wald',
      'biome_mountain': 'Berg',
      'biome_sea': 'Meer',
      'biome_desert': 'Wüste',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Vulkan',
      'biome_wetland': 'Feuchtgebiet',
      'biome_celestial_crater': 'Himmelskrater',
      'biome_celestialCrater': 'Himmelskrater',
      'biome_kurgan_valley': 'Ahnental-Kurgan',
      'biome_kurganValley': 'Ahnental-Kurgan',
      'biome_crystal_chasm': 'Kristallklamm',
      'biome_crystalChasm': 'Kristallklamm',
      'corn_name': 'Weizenfeld',
      'corn_desc': 'Produziert Weizen und Vorräte.',
      'barley_name': 'Gerstenfeld',
      'barley_desc': 'Frostresistentes Getreide für kaltes Klima.',
      'pasture_name': 'Steppenweide',
      'pasture_desc': 'Weidetiere und Steppenpferde; hohe Nahrungsproduktion.',
      'orchard_name': 'Obstgarten',
      'orchard_desc': 'Wilde Früchte mit Sommer- und Herbstschub.',
      'quarry_name': 'Steinbruch',
      'quarry_desc': 'Bricht reine Steinblöcke für den Bau.',
      'resin_camp_name': 'Harz- & Birkenhütte',
      'resin_camp_desc': 'Erntet Birkenholz und Dämmmaterial.',
      'lumberjack_name': 'Holzfällerhütte',
      'lumberjack_desc': 'Produziert Holz.',
      'windmill_name': 'Windmühle',
      'windmill_desc': 'Mahlt Nahrung zu Mehl.',
      'sawmill_name': 'Sägewerk',
      'sawmill_desc': 'Verarbeitet Holz zu Brettern.',
      'bakery_name': 'Steinofen-Bäckerei',
      'bakery_desc': 'Backt Brot.',
      'furniture_name': 'Schreinerhütte',
      'furniture_desc': 'Stellt Möbel her.',
      'worker_name': 'Arbeiterhütte',
      'worker_desc': 'Automatisiert Transport.',
      'watchtower_name': 'Wachturm',
      'watchtower_desc': 'Erhellt Nebel.',
      'mine_name': 'Mine',
      'mine_desc': 'Fördert Stein und Eisen.',
      'bridge_name': 'Holzbrücke',
      'bridge_desc': 'Überquert Wasser.',
      'fisherman_name': 'Fischer',
      'fisherman_desc': 'Produziert Nahrung auf Wasser.',
      'fisherman_hut_name': 'Fischerhütte',
      'fisherman_hut_desc': 'Sammelpunkt für Fischer.',
      // Desert
      'oasis_cistern_name': 'Oasenzisterne',
      'oasis_cistern_desc': 'Beseitigt Dürre und gewährt +40% Fruchtbarkeits-Aura.',
      'caravanserai_name': 'Seidenstraßen-Karawanserei',
      'caravanserai_desc': 'Tauscht Waren gegen Brot und Vorräte.',
      'astrolabe_name': 'Wüsten-Astrolabium',
      'astrolabe_desc': 'Erforscht die Wüstensterne.',
      // Tundra
      'reindeer_sanctuary_name': 'Rentier-Jurte',
      'reindeer_sanctuary_desc': 'Produziert kälteresistente Nahrung.',
      'geothermal_bath_name': 'Thermalbad',
      'geothermal_bath_desc': 'Verdoppelt das Arbeitertempo durch Wärme.',
      'permafrost_dig_name': 'Permafrost-Bohrung',
      'permafrost_dig_desc': 'Fördert Mammutfossilien und Eisenerz.',
      // Volcano
      'steam_vent_name': 'Dampfschlot',
      'steam_vent_desc': 'Erzeugt Dampfdruck und Stein.',
      'obsidian_forge_name': 'Obsidianschmiede',
      'obsidian_forge_desc': 'Schmiedet Obsidianwerkzeuge und Eisen.',
      // Wetland
      'herbalist_yurt_name': 'Kräuterjurte',
      'herbalist_yurt_desc': 'Braut heilsame Nahrung aus Feuchtgebiet-Pflanzen.',
      'scribe_workshop_name': 'Schreibwerkstatt',
      'scribe_workshop_desc': 'Schöpft alte Schriftrollen und Bretter.',
      // Legendary
      'celestial_anvil_name': 'Himmelsamboss',
      'celestial_anvil_desc': 'Schmiedet Meteoreisen aus Meteoriten.',
      'ancestral_totem_name': 'Ahnentotem',
      'ancestral_totem_desc': 'Kanalisiert das Erbe aller Wanderungen.',
      'prismatic_resonator_name': 'Kristallresonator',
      'prismatic_resonator_desc': 'Verdoppelt die Kraft aller heiligen Schreine.',
      // New Mechanic Buildings
      'granary_vault_name': 'Kurgan-Gewölbe',
      'granary_vault_desc': 'Logistiklager, das das Sammeltempo im Umkreis von 3 Hexfeldern um +50% steigert.',
      'kumis_yurt_name': 'Kumis-Jurte',
      'kumis_yurt_desc': 'Fermentiert Stutenmilch zum traditionellen Steppen-Kumys.',
      'felt_tent_workshop_name': 'Filzzelt-Werkstatt',
      'felt_tent_workshop_desc': 'Verarbeitet Wolle zu strapazierfähigem Filz für Jurten und Handel.',
      'damascus_forge_name': 'Damast-Schmiede',
      'damascus_forge_desc': 'Schmiedet feinsten Damaszenerstahl in Mehrlagen-Technik.',
      'runic_stele_name': 'Orchon-Runenstele',
      'runic_stele_desc': 'Hält altes Steppenwissen fest und erzeugt Weisheit für den Töre-Baum.',
      'market_title': 'Steppenbasar',
      'market_desc': 'Tausche Waren gegen Stein, Eisen und Ruhm.',
      'trade': 'Tauschen',
      'tore_title': 'Töre & Rat',
      'tore_desc': 'Stärke dein Reich mit alten Traditionen und Titeln.',
      'learn_talent': 'Lernen',
      'claim_title': 'Titel beanspruchen',
      'warm_tile': 'Wärmen (+50%)',
      'locked_castle_lvl': 'Erfordert Jurte Stufe {0}',
      'logistics_capacity': 'Tragfähigkeit',
      'logistics_utilized': 'Genutzt',
      'logistics_idle': 'Frei',
      'logistics_load': 'Logistiklast',
      'capacity': 'Kapazität',
      'in_coverage_buildings': '{0} Produktionsbauten in Reichweite',
      'resource_breakdown_title': 'Produktions- & Verbrauchsübersicht',
      'total_production': 'Gesamtproduktion',
      'total_consumption': 'Gesamtverbrauch',
      'net_total_label': 'Nettobilanz',
      'producers_label': 'PRODUZENTEN',
      'consumers_label': 'VERBRAUCHER',
      'no_active_buildings': 'Keine aktiven Bauten für diesen Rohstoff.',
      'hexpedia_title': 'HEXPEDIA - STEPPEN-ENZYKLOPÄDIE',
      'hexpedia_search_hint': 'Mechaniken, Gebäude oder Biome suchen...',
      'hexpedia_stats': 'MECHANIK-DATEN & FORMELN',
      'hexpedia_step_guide': 'SCHRITT-FÜR-SCHRITT-ANLEITUNG',
      'hexpedia_tips': 'TAKTIK-TIPPS',
      'hexpedia_empty': 'Keine passenden Mechaniken gefunden.',
    },
  };

  static String get(String key, {String lang = 'tr', List<String>? args}) {
    final map = _strings[lang] ?? _strings['tr']!;
    String result = map[key] ?? key;
    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        result = result.replaceAll('{$i}', args[i]);
      }
    }
    return result;
  }
}
