class GameLocalization {
  static const List<String> supportedLanguages = ['tr', 'en', 'es', 'de'];

  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'game_title': 'HexRush Kağanlığı',
      'food': 'Gıda',
      'wood': 'Odun',
      'flour': 'Un',
      'plank': 'Kereste',
      'bread': 'Ekmek',
      'furniture': 'Mobilya',
      'stone': 'Taş',
      'iron': 'Demir',
      'crowns': 'Kut / Şan',
      'land': 'Toprak',
      'spring': 'Bahar',
      'summer': 'Yaz',
      'autumn': 'Sonbahar',
      'winter': 'Kış',
      'season_spring': 'Bahar Geldi',
      'season_summer': 'Yaz Sıcağı Başladı',
      'season_autumn': 'Güz Hasadı Başladı',
      'season_winter': 'Kış Ayazı Bastırdı',
      'zud_blizzard_alert': 'DİKKAT: Şiddetli Zud Afeti!',
      'spring_bonus_desc': 'Sürüler coşuyor, bereket ve taze filizler',
      'summer_bonus_desc': 'Gıda ve ekmek üretimi zirvede',
      'autumn_bonus_desc': 'Odun ve kereste verimi +%25, hasat vakti',
      'winter_penalty_desc': 'Don ve ayaz: Gıda üretimi %50 yavaşlar',
      'zud_production_penalty': 'Kritik don: Tüm üretimler -%40 yavaşlar!',
      'year': 'Yıl',
      'conquer': 'Toprağı Fethet',
      'cost': 'Maliyet',
      'free': 'ÜCRETSİZ',
      'build': 'İnşa Et',
      'upgrade': 'Geliştir',
      'collect': 'Topla',
      'level': 'Seviye',
      'per_sec': '/sn',
      'frenzy_boost': '10x Toy Coşkusu',
      'settings': 'Ayarlar',
      'privacy_policy': 'Gizlilik Politikası',
      'language': 'Dil',
      'sound': 'Ses',
      'mute': 'Sessize Al',
      'reset_game': 'Oyunu Sıfırla',
      'castle_title': 'Kağan Otağı',
      'castle_desc': 'Kağanlığın kalbi. Otağ büyüdükçe töreler ve yeni yapılar açılır.',
      'global_bonus': 'Küresel Hız Bonusu',
      'next_unlock': 'Sonraki Kilit Açılımı',
      'biome_meadow': 'Çayır',
      'biome_forest': 'Orman',
      'biome_mountain': 'Dağ',
      'biome_sea': 'Deniz',
      'biome_desert': 'Karakum Çölü',
      'biome_tundra': 'Altay Tundrası',
      'biome_volcano': 'Yanardağ',
      'biome_wetland': 'Bozkır Sazlığı',
      'biome_celestial_crater': 'Göksel Krater',
      'biome_celestialCrater': 'Göksel Krater',
      'biome_kurgan_valley': 'Atalar Kurganı',
      'biome_kurganValley': 'Atalar Kurganı',
      'biome_crystal_chasm': 'Kristal Yarığı',
      'biome_crystalChasm': 'Kristal Yarığı',
      'corn_name': 'Buğday Tarlası',
      'corn_desc': 'Temel buğday ve erzak üretimi yapar.',
      'barley_name': 'Arpa & Darı Tarlası',
      'barley_desc': 'Soğuğa dayanıklı bozkır tahılı; kış ayazında da üretir.',
      'pasture_name': 'Bozkır Otlağı & Hara',
      'pasture_desc': 'Bozkır atları ve sürü otlağı; yüksek iaşe ve et üretir.',
      'orchard_name': 'Yemişlik Bahçesi',
      'orchard_desc': 'Yaz ve sonbaharda coşan dağ meyveleri bahçesi.',
      'quarry_name': 'Taş Yonma Ocağı',
      'quarry_desc': 'Otağ ve sur inşası için saf taş kütleleri çıkarır.',
      'resin_camp_name': 'Katran & Huş Otağı',
      'resin_camp_desc': 'Yurt yalıtımı ve otağ direkleri için kaliteli huş odunu üretir.',
      'lumberjack_name': 'Hızar & Oduncu Otağı',
      'lumberjack_desc': 'Temel odun üretimi yapar.',
      'windmill_name': 'Yel Değirmeni',
      'windmill_desc': 'Gıdayı Un\'a çevirir.',
      'sawmill_name': 'Hızar Otağı',
      'sawmill_desc': 'Odunu Kalas\'a çevirir.',
      'bakery_name': 'Taş Köz Fırını',
      'bakery_desc': 'Un ve Gıdadan Ekmek üretir.',
      'furniture_name': 'Marangoz Otağı',
      'furniture_desc': 'Kalas ve Odundan Mobilya üretir.',
      'worker_name': 'İşçi Kulübesi',
      'worker_desc': 'Otomatik hammadde taşır.',
      'watchtower_name': 'Savunma & Gözcü Kulesi',
      'watchtower_desc': '3 Hex menzilli okçu kulesi; yaklaşan akıncıları otomatik vurur.',
      'mine_name': 'Maden Ocağı',
      'mine_desc': 'Taş ve demir çıkarır.',
      'bridge_name': 'Ahşap Köprü',
      'bridge_desc': 'Deniz geçişini sağlar.',
      'fisherman_name': 'Balıkçı',
      'fisherman_desc': 'Su üzerinden gıda üretimi yapar.',
      'fisherman_hut_name': 'Balıkçı Barınağı',
      'fisherman_hut_desc': 'Balıkçılar için toplama noktasıdır.',
      'oasis_cistern_name': 'Vaha Sarnıcı',
      'oasis_cistern_desc': 'Çöl kuraklığını siler, etrafa +%40 verim aurası yayar.',
      'caravanserai_name': 'İpek Yolu Kervansarayı',
      'caravanserai_desc': 'Kervan ticaretiyle ekmek ve erzak kazandırır.',
      'astrolabe_name': 'Gök Gözlemevi',
      'astrolabe_desc': 'Çöl gecelerinde yıldızları haritalar.',
      'reindeer_sanctuary_name': 'Geyik Otağı',
      'reindeer_sanctuary_desc': 'Dondurucu ayaza dirençli gıda üretir.',
      'geothermal_bath_name': 'Jeotermal Kaplıca',
      'geothermal_bath_desc': 'Sıcak mineral buharıyla işçi hızını 2x yapar.',
      'permafrost_dig_name': 'Kehribar Sondajı',
      'permafrost_dig_desc': 'Donmuş topraktan mamut fosili ve demir çıkarır.',
      'steam_vent_name': 'Buhar Bacası',
      'steam_vent_desc': 'Jeotermal buhar basıncıyla enerji ve taş üretir.',
      'obsidian_forge_name': 'Obsidyen Dökümhanesi',
      'obsidian_forge_desc': 'Obsidyen aletlerle demir ve taş işler.',
      'herbalist_yurt_name': 'Şifacı Otağı',
      'herbalist_yurt_desc': 'Sazlık nilüferlerinden şifalı gıda üretir.',
      'scribe_workshop_name': 'Yazıt Atölyesi',
      'scribe_workshop_desc': 'Kamışlardan antik parşömen ve kalas üretir.',
      'celestial_anvil_name': 'Gök Demircisi',
      'celestial_anvil_desc': 'Göktaşından nadir Gök Demiri ve çelik döver.',
      'ancestral_totem_name': 'Kurgan Koruyucusu',
      'ancestral_totem_desc': 'Tüm geçmiş göçlerin kümülatif bereketiyle üretimi katlar.',
      'prismatic_resonator_name': 'Rezonans Kulesi',
      'prismatic_resonator_desc': 'Tüm kutlu tapınakların gücünü ikiye katlar.',
      'granary_vault_name': 'Kurgan Mahzeni',
      'granary_vault_desc': '3 hex menzildeki binaların taşıma ve hasat hızını +%50 artırır.',
      'kumis_yurt_name': 'Kımızın Otağı',
      'kumis_yurt_desc': 'At sütü fermente eden otağ; değerli göçebe kımız içeceği üretir.',
      'felt_tent_workshop_name': 'Keçe Çadırhanesi',
      'felt_tent_workshop_desc': 'Yün işleyip çadırlar ve ticaret için dayanıklı keçe üretir.',
      'damascus_forge_name': 'Şam Çeliği Dökümhanesi',
      'damascus_forge_desc': 'Kat kat dövme çelik ocağı; yüksek nitelikli Şam Çeliği üretir.',
      'runic_stele_name': 'Orhun Bitig Taşı',
      'runic_stele_desc': 'Töre Bilgelik Ağacı için kadim bozkır yazıtı ve bilgelik üretir.',
      'market_title': 'Bozkır Kurultay Pazarı',
      'market_desc': 'Ürettiğin malları takasla taş, demir ve hanlık şanına dönüştür.',
      'trade': 'Takas Et',
      'tore_title': 'Töre & Kurultay',
      'tore_desc': 'Kadim töre yetenekleri ve unvanlarla kağanlığını güçlendir.',
      'learn_talent': 'Öğren',
      'claim_title': 'Unvanı Al',
      'warm_tile': 'Isıt (+%50 Hız)',
      'locked_castle_lvl': 'Otağ Seviye {0} Gerekli',
      'logistics_capacity': 'Taşıma Kapasitesi',
      'logistics_utilized': 'Kullanılan',
      'logistics_idle': 'Boşta',
      'logistics_load': 'Lojistik Yükü',
      'capacity': 'Kapasite',
      'in_coverage_buildings': '{0} Üretim Yapısı Menzilde',
      'resource_breakdown_title': 'Üretim & Tüketim Dökümü',
      'total_production': 'Toplam Üretim',
      'total_consumption': 'Toplam Tüketim',
      'net_total_label': 'Net Bilanço',
      'gross_production': 'Brüt Üretim Kapasitesi',
      'net_transported': 'Net Taşınabilir Gelir',
      'logistics_bottleneck': 'Lojistik Darboğazı',
      'uncollected_surplus_warning': 'Yetersiz taşıma kapasitesi veya 4 Hex menzil dışı nedeniyle üretim fazlası binada birikiyor. İşçi Kulübesi veya Tahıl Mahzeni kurarak taşıma menzil ve kapasitesini artırın.',
      'producers_label': 'ÜRETİCİLER',
      'consumers_label': 'TÜKETİCİLER',
      'no_active_buildings': 'Bu kaynak için aktif üretim veya tüketim yapan bina yok.',
      'hexpedia_title': 'HEXPEDIA - BOZKIR ANSİKLOPEDİSİ',
      'hexpedia_search_hint': 'Mekanik, bina veya biyom ara...',
      'hexpedia_stats': 'MEKANİK VERİLERİ & FORMÜLLER',
      'hexpedia_step_guide': 'ADIM ADIM UYGULAMA REHBERİ',
      'hexpedia_tips': 'TAKTİKSEL BOZKIR İPUÇLARI',
      'hexpedia_empty': 'Arama kriterine uygun mekanik veya rehber bulunamadı.',
      'welcome_khan': 'HOŞ GELDİNİZ, BOZKIR KAĞANI',
      'cancel': 'İptal',
      'confirm': 'Onayla',
      'yes': 'Evet',
      'no': 'Hayır',
      'close': 'Kapat',
      'skip': 'ATLA',
      'prev': 'GERİ',
      'next': 'İLERİ',
      'start_adventure': 'MACERAYA BAŞLA',
      'dawn_of_steppe': 'BOZKIRIN DOĞUŞU',
      'great_migration_title': 'Büyük Göç & Kanatlı Hanlık',
      'great_migration_confirm_title': 'Büyük Göçü Onayla',
      'great_migration_confirm_desc': 'Tüm binalar ve kaynaklar sıfırlanacak, ancak Kut / Taç ve Tamga kazanarak kalıcı bonuslar elde edeceksiniz. Devam etmek istiyor musunuz?',
      'confirm_migration_btn': 'EVET, GÖÇÜ BAŞLAT',
      'crowns_to_gain': 'KAZANILACAK TAÇ',
      'ancestral_tamga': 'ATALAR TAMGASI',
      'kut_multiplier': 'KUT KATSAYISI',
      'migrant_memory_title': 'GÖÇMEN HAFIZASI',
      'total_migrations': 'TOPLAM GÖÇ',
      'tamga_count': 'TAMGA SAYISI',
      'permanent_bonus': 'KALICI BONUS',
      'no_migrations_yet': 'Henüz bir Büyük Göç tamamlanmadı.\nİlk göçünüz sonrasında kadim bozkır hafızası burada kaydedilecektir.',
      'horn_of_steppe_title': 'BOZKIR AKINI',
      'raid_info_title': 'AKIN BİLGİSİ & SAVUNMA PLANI',
      'sfx_effects': 'SES EFEKTLERİ',
      'music_steppe': 'BOZKIR MÜZİĞİ',
      'on': 'AÇIK',
      'off': 'KAPALI',
      'notification_prefs': 'BİLDİRİM TERCİHLERİ',
      'storage_full_alert': 'Ambar Dolum Uyarısı (%80)',
      'season_change_alert': 'Mevsim Değişimi Uyarısı',
      'quest_completed_alert': 'Görev Tamamlanma Uyarısı',
      'castle_upgrade_alert': 'Otağ Büyütme Hazır Uyarısı',
      'theme_palette': 'NEO-BRUTALİST TEMA PALETİ',
      'great_migration_screen_btn': 'BÜYÜK GÖÇ & SIFIRLAMA EKRANI',
      'steppe_story_btn': 'BOZKIR DESTANI (GİRİŞ HİKAYESİ)',
      'reward_claiming': 'ÖDÜL ALINIYOR',
      'reward_please_wait': 'Ödül alınıyor lütfen bekleyiniz...',
      'crown_breakdown_title': 'ŞAN & TAÇ DÖKÜMÜ',
      'reset_calculation_subtitle': 'Büyük Göç Sıfırlama Hesabı',
      'diorama_snapshot_title': 'BOZKIR DİORAMA FOTOĞRAFI',
      'diorama_saved_toast': 'Diorama fotoğrafı galeriye kaydedildi!',
      'realm_selection_title': 'HANLIK DİYARI SEÇİMİ',
      'steppe_lore_tree_title': 'TÖRE BİLGELİK AĞACI',
      'wisdom': 'Bilgelik',
      'claim': 'Al',
      'claimed': 'Alındı',
      'locked': 'Kilitli',
      'unlock': 'Kilit Aç',
      'equipped': 'TAKILI',
      'equip': 'TAK',
      'active': 'AKTİF',
      'inactive': 'PASİF',
      'hours': 'saat',
      'minutes': 'dakika',
      'seconds': 'saniye',
      'owned': 'MÜLK',
      'wild': 'SAHİPSİZ',
      'loading_title': 'KADİM BOZKIR MATRİSİ',
      'loading_subtitle': 'İzometrik Voksel Motoru Aktif Ediliyor...',
      'loading_label': 'YÜKLENİYOR',
      'lore_tree_title': 'ORHUN BİTİG TAŞLARI & TÖRE AĞACI',
      'bitig_label': 'BİTİG',
      'branch_logistics': 'Lojistik',
      'branch_heating': 'Isınma',
      'branch_soil': 'Toprak',
      'branch_casting': 'Döküm',
      'node_unlocked': 'AÇILDI',
      'trade_orders_title': 'İPEK YOLU ELÇİ SİPARİŞLERİ',
      'no_envoy_orders': 'Şu anda bekleyen elçi buyruğu bulunmuyor.',
      'order_delivered': 'TESLİM EDİLDİ',
      'deliver_order_btn': 'BUYRUĞU TESLİM ET',
      'realm_active': 'AKTİF DİYAR',
      'select_realm_btn': 'BU DİYARI SEÇ',
      'realm_altay_name': 'ALTAY GÖKSEL PLATOLARI',
      'realm_altay_sub': 'Madenler, Taş Ocakları ve Şam Çeliği Bereketi',
      'realm_altay_desc': '• Taş, Demir ve Şam Çeliği üretimi 2 Katına çıkar.\n• Dağ ve Krater arazisi fetih maliyetinde %30 indirim.\n• Sert kışlar ve yüksek Kurgan mirası sinerjisi.',
      'realm_idil_name': 'İDİL-YAYIK NEHİR HAVZASI',
      'realm_idil_sub': 'Balıkçılık, Sulak Alanlar ve Kımız Otağı Bereketi',
      'realm_idil_desc': '• Balık, Gıda, Un ve Kımız üretimi 2 Katına çıkar.\n• Deniz ve Sazlık arazisi fetih maliyetinde %30 indirim.\n• Nehir ve göl komşuluğunda +%50 bereket rezonansı.',
      'realm_karakum_name': 'KARAKUM & TARIM VAHALARI',
      'realm_karakum_sub': 'İpek Yolu Kervanları, Pazar Takası ve Keçe Bereketi',
      'realm_karakum_desc': '• Kervan hızı, Pazar takas karları ve Taç getirisi 2 Katına çıkar.\n• Keçe ve çadır üretimi %50 daha hızlıdır.\n• Çöl ve vaha arazisi fetih maliyetinde %25 indirim.',
      'migration_confirm_title': 'BÜYÜK GÖÇÜ ONAYLIYOR MUSUNUZ?',
      'migration_confirm_body': 'Mevcut topraklarınız ve hammaddeleriniz sıfırlanacak; obanız yeni çağa göç edecektir.\n\nKazanılacak Miras:\n• +{0} Taç (Şan & Kut Puanı)\n• +{1} Kalıcı Atalar Tamgası\n• Binalarınız Ata Kurganlarına dönüşecek.\n\nDevam etmek istediğinizden emin misiniz?',
      'migration_header_title': 'BÜYÜK GÖÇ (PRESTİJ & KUT KATLAYICI)',
      'migration_cycle_subtitle': 'Bozkırın Ebedi Zafer Döngüsü ve Miras Katsayısı',
      'migration_legacy_header': 'BU GÖÇTE KAZANILACAK KALICI MİRAS',
      'migration_breakdown_title': 'KAZANIM & MİRAS DAĞILIM LİSTESİ',
      'migration_oaths_title': 'KUTSAL ANDLAR (MEYDAN OKUMA MODİFİKATÖRLERİ)',
      'migration_target_realm_title': 'HEDEF SEFER DİYARI SEÇİMİ',
      'migration_resources_label': 'Hammaddeler',
      'migration_victories_title': 'EBEDİ DEVLET ZAFERLERİ:',
      'migration_victory_bengutas': 'Orhun Bengü Taşları (Kültürel)',
      'migration_victory_silkroad': 'Ulu İpek Yolu Ağı (Lojistik)',
      'migration_victory_realms': '4 Kadim Diyar Hakimiyeti (Coğrafi)',
      'migration_oath_iron_title': 'Yalın Kılıç Andı (+%15 Kut)',
      'migration_oath_iron_desc': 'Maden & demir odaklı ilerleme • Ekstra Tamga bereketi',
      'migration_oath_frost_title': 'Buzul Çağı Andı (+%15 Kut)',
      'migration_oath_frost_desc': 'Kış ve Zud boranlarına karşı çetin direnç',
      'migration_realm_steppe_title': 'Ulu Bozkır (Standart)',
      'migration_realm_steppe_desc': 'Dengeli çayır, orman ve maden havzaları',
      'migration_realm_silk_title': 'İpek Yolu Vahaları',
      'migration_realm_silk_desc': 'Çöl biyomları, kervansaraylar ve yüksek ticaret geliri',
      'migration_realm_altay_title': 'Altay Yaylaları',
      'migration_realm_altay_desc': 'Tundra ve jeotermal kaplıcalarla don çetinliği',
      'migration_not_ready_warning': 'Oba henüz göçe hazır değil (Gereken: Otağ Sv. 5 ve en az 12 Karo)',
      'migration_not_ready_toast': 'Göç için Kağan Otağı Sv. 5 ve 12 Karo gereklidir.',
      'start_migration_btn': 'BÜYÜK GÖÇÜ BAŞLAT',
      'migration_locked_btn': 'GÖÇ KİLİTLİ',
      'realm_selected_badge': 'SEÇİLDİ',
      'fish': 'Balık',
      'kumis': 'Kımız',
      'felt': 'Keçe',
      'damascus_steel': 'Şam Çeliği',
      'offline_gains_title': 'BOZKIR ÇEVRİMDIŞI KAZANCI',
      'offline_gains_toast': 'Çevrimdışı bozkır kazancı ambara aktarıldı.',
      'offline_gains_boosted_toast': 'Bozkır bereketiyle 2.0x çift kat çevrimdışı kazanç ambara aktarıldı!',
      'lore_logistics_1_title': 'Çevik Atlı Posta',
      'lore_logistics_1_desc': 'İşçi taşıma menzilini +1 Hex genişletir ve kervan hızını +%25 artırır.',
      'lore_logistics_2_title': 'İpek Yolu Ağı',
      'lore_logistics_2_desc': 'Kervan yollarının ticaret sinerjisini +%50 artırır.',
      'lore_logistics_3_title': 'Kağanlık Kurye Teşkilatı',
      'lore_logistics_3_desc': 'Tüm haritada işçi taşıma kapasitesini 2 katına çıkarır.',
      'lore_weather_1_title': 'Kalın Keçe Dokuma',
      'lore_weather_1_desc': 'Kışın donan karoların ısıtma odun maliyetini %30 azaltır.',
      'lore_weather_2_title': 'Ocak Başı Ateşi',
      'lore_weather_2_desc': 'Isıtılan karoların kışın üretim çarpanını +%40 artırır.',
      'lore_weather_3_title': 'Zud Direnci',
      'lore_weather_3_desc': 'Zud fırtınasının negatif üretim cezasını yarı yarıya düşürür.',
      'lore_soil_1_title': 'Yaylak-Kışlak Göçü',
      'lore_soil_1_desc': 'Nadasa bırakılan çayırlarda toprak sağlığı yenilenme hızını 2x yapar.',
      'lore_soil_2_title': 'Kutlu Tohum Islahı',
      'lore_soil_2_desc': 'Tüm tarla ve meyve bahçelerinde temel hasat verimini +%35 artırır.',
      'lore_soil_3_title': 'Toprak Nefesi Patlaması',
      'lore_soil_3_desc': 'Dinlenmiş toprağın nefes patlaması (respiration burst) çarpanını 3 katına çıkarır.',
      'lore_metal_1_title': 'Körük Ocağı Islahı',
      'lore_metal_1_desc': 'Madenlerden cevher ve demir çıkarma hızını +%30 artırır.',
      'lore_metal_2_title': 'Şam Çeliği Sırrı',
      'lore_metal_2_desc': 'Şam Çeliği dökümhanesi verimini +%50 artırır.',
      'lore_metal_3_title': 'Mete Han Yay & Kılıçları',
      'lore_metal_3_desc': 'Tüm maden ve zanaat yapılarının küresel verimini 2 katına çıkarır.',
    },
    'en': {
      'game_title': 'HexRush Khaganate',
      'food': 'Food',
      'wood': 'Wood',
      'flour': 'Flour',
      'plank': 'Plank',
      'bread': 'Bread',
      'furniture': 'Furniture',
      'stone': 'Stone',
      'iron': 'Iron',
      'crowns': 'Glory / Renown',
      'land': 'Land',
      'spring': 'Spring',
      'summer': 'Summer',
      'autumn': 'Autumn',
      'winter': 'Winter',
      'season_spring': 'Spring Has Arrived',
      'season_summer': 'Summer Has Begun',
      'season_autumn': 'Autumn Harvest Has Begun',
      'season_winter': 'Winter Frost Has Fallen',
      'zud_blizzard_alert': 'WARNING: Severe Zud Blizzard!',
      'spring_bonus_desc': 'Herds thrive, pasture fertility surges',
      'summer_bonus_desc': 'Food and grain production at peak',
      'autumn_bonus_desc': 'Wood and lumber yield +25%, harvest time',
      'winter_penalty_desc': 'Frost and cold: Food yields reduced by 50%',
      'zud_production_penalty': 'Critical blizzard: All production reduced by 40%!',
      'year': 'Year',
      'conquer': 'Conquer Land',
      'cost': 'Cost',
      'free': 'FREE',
      'build': 'Build',
      'upgrade': 'Upgrade',
      'collect': 'Collect',
      'level': 'Level',
      'per_sec': '/s',
      'frenzy_boost': '10x Steppe Surge',
      'settings': 'Settings',
      'privacy_policy': 'Privacy Policy',
      'language': 'Language',
      'sound': 'Sound',
      'mute': 'Mute',
      'reset_game': 'Reset Game',
      'castle_title': 'Khan\'s Yurt',
      'castle_desc': 'The heart of your steppe realm. Expands traditions and unlocks new structures.',
      'global_bonus': 'Global Speed Bonus',
      'next_unlock': 'Next Unlock',
      'biome_meadow': 'Meadow',
      'biome_forest': 'Forest',
      'biome_mountain': 'Mountain',
      'biome_sea': 'Sea',
      'biome_desert': 'Desert',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Volcano',
      'biome_wetland': 'Wetlands',
      'biome_celestial_crater': 'Celestial Crater',
      'biome_celestialCrater': 'Celestial Crater',
      'biome_kurgan_valley': 'Ancestral Kurgan',
      'biome_kurganValley': 'Ancestral Kurgan',
      'biome_crystal_chasm': 'Crystal Chasm',
      'biome_crystalChasm': 'Crystal Chasm',
      'corn_name': 'Wheat Field',
      'corn_desc': 'Produces staple wheat and provisions.',
      'barley_name': 'Barley Field',
      'barley_desc': 'Frost-resilient steppe grain that yields in cold weather.',
      'pasture_name': 'Steppe Pasture',
      'pasture_desc': 'Grazing herds and steppe horses; high food and meat yield.',
      'orchard_name': 'Steppe Orchard',
      'orchard_desc': 'Wild fruits that surge in summer and autumn.',
      'quarry_name': 'Stone Quarry',
      'quarry_desc': 'Excavates pure stone blocks for khaganate construction.',
      'resin_camp_name': 'Birch & Resin Camp',
      'resin_camp_desc': 'Harvests high quality birch timber and yurt insulation.',
      'lumberjack_name': 'Lumberjack Lodge',
      'lumberjack_desc': 'Produces timber.',
      'windmill_name': 'Windmill',
      'windmill_desc': 'Converts Food into Flour.',
      'sawmill_name': 'Timber Mill',
      'sawmill_desc': 'Converts Wood into Planks.',
      'bakery_name': 'Stone Hearth Bakery',
      'bakery_desc': 'Produces Bread from Flour & Food.',
      'furniture_name': 'Carpenter Lodge',
      'furniture_desc': 'Produces Furniture from Planks.',
      'worker_name': 'Worker Hut',
      'worker_desc': 'Automates resource collection.',
      'watchtower_name': 'Defense Watchtower',
      'watchtower_desc': '3-Hex range archer tower; automatically shoots approaching enemies.',
      'mine_name': 'Mine Quarry',
      'mine_desc': 'Produces Stone and Iron.',
      'bridge_name': 'Wooden Bridge',
      'bridge_desc': 'Allows crossing water tiles.',
      'fisherman_name': 'Fisherman',
      'fisherman_desc': 'Produces food from water tiles.',
      'fisherman_hut_name': 'Fisherman Hut',
      'fisherman_hut_desc': 'Collection point for fishermen.',
      'oasis_cistern_name': 'Oasis Cistern',
      'oasis_cistern_desc': 'Clears drought and gives +40% fertility aura.',
      'caravanserai_name': 'Silk Road Caravanserai',
      'caravanserai_desc': 'Trades goods for bread and wealth.',
      'astrolabe_name': 'Desert Astrolabe',
      'astrolabe_desc': 'Maps desert stars for celestial guidance.',
      'reindeer_sanctuary_name': 'Reindeer Sanctuary',
      'reindeer_sanctuary_desc': 'Produces frost-resilient food and warmth.',
      'geothermal_bath_name': 'Geothermal Bath',
      'geothermal_bath_desc': 'Doubles worker speed with warm spring steam.',
      'permafrost_dig_name': 'Permafrost Dig',
      'permafrost_dig_desc': 'Excavates mammoth fossils and iron ore.',
      'steam_vent_name': 'Steam Vent Dynamo',
      'steam_vent_desc': 'Generates steam pressure and stone.',
      'obsidian_forge_name': 'Obsidian Master Forge',
      'obsidian_forge_desc': 'Forges obsidian-hardened tools and iron.',
      'herbalist_yurt_name': 'Herbalist Yurt',
      'herbalist_yurt_desc': 'Brews nourishing remedies from wetland flora.',
      'scribe_workshop_name': 'Reed Scribe Workshop',
      'scribe_workshop_desc': 'Crafts ancient scrolls and planks.',
      'celestial_anvil_name': 'Celestial Anvil',
      'celestial_anvil_desc': 'Forges rare Meteoric Steel from fallen meteorites.',
      'ancestral_totem_name': 'Ancestral Totem',
      'ancestral_totem_desc': 'Channels cumulative migration heritage.',
      'prismatic_resonator_name': 'Prismatic Resonator',
      'prismatic_resonator_desc': 'Doubles the power of all sacred shrines.',
      'granary_vault_name': 'Kurgan Vault',
      'granary_vault_desc': 'Logistics storehouse boosting collection speed of nearby buildings within 3 hexes by +50%.',
      'kumis_yurt_name': 'Kumis Yurt',
      'kumis_yurt_desc': 'Ferments mare milk to brew traditional steppe kumis.',
      'felt_tent_workshop_name': 'Felt Tent Workshop',
      'felt_tent_workshop_desc': 'Processes raw wool into sturdy felt for yurts and commerce.',
      'damascus_forge_name': 'Damascus Master Forge',
      'damascus_forge_desc': 'Forges Damascus steel ingots through layered metallurgy.',
      'runic_stele_name': 'Orkhon Runic Stele',
      'runic_stele_desc': 'Inscribes ancient steppe knowledge to generate Lore for the Töre tree.',
      'market_title': 'Steppe Bazaar',
      'market_desc': 'Trade goods for stone, iron, and glory.',
      'trade': 'Trade',
      'tore_title': 'Töre & Council',
      'tore_desc': 'Empower your realm with ancient traditions and titles.',
      'learn_talent': 'Learn',
      'claim_title': 'Claim Title',
      'warm_tile': 'Warm (+50% Speed)',
      'locked_castle_lvl': 'Requires Yurt Lv.{0}',
      'logistics_capacity': 'Hauling Capacity',
      'logistics_utilized': 'Utilized',
      'logistics_idle': 'Idle',
      'logistics_load': 'Logistics Load',
      'capacity': 'Capacity',
      'in_coverage_buildings': '{0} Production Buildings in Range',
      'resource_breakdown_title': 'Production & Consumption Breakdown',
      'total_production': 'Total Production',
      'total_consumption': 'Total Consumption',
      'net_total_label': 'Net Balance',
      'gross_production': 'Gross Production Rate',
      'net_transported': 'Net Transported Income',
      'logistics_bottleneck': 'Logistics Bottleneck',
      'uncollected_surplus_warning': 'Surplus production is accumulating due to limited hauling capacity or being out of 4-hex range. Build Worker Huts or Granary Vaults to increase capacity.',
      'producers_label': 'PRODUCERS',
      'consumers_label': 'CONSUMERS',
      'no_active_buildings': 'No active buildings producing or consuming this resource.',
      'hexpedia_title': 'HEXPEDIA - STEPPE ENCYCLOPEDIA',
      'hexpedia_search_hint': 'Search mechanics, buildings or biomes...',
      'hexpedia_stats': 'MECHANIC STATS & FORMULAS',
      'hexpedia_step_guide': 'STEP-BY-STEP GUIDE',
      'hexpedia_tips': 'TACTICAL STEPPE TIPS',
      'hexpedia_empty': 'No matching mechanics or guides found.',
      'welcome_khan': 'WELCOME, KHAGAN OF THE STEPPE',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'skip': 'SKIP',
      'prev': 'PREV',
      'next': 'NEXT',
      'start_adventure': 'BEGIN ADVENTURE',
      'dawn_of_steppe': 'DAWN OF THE STEPPE',
      'great_migration_title': 'Great Migration & Realm Renewal',
      'great_migration_confirm_title': 'Confirm Great Migration',
      'great_migration_confirm_desc': 'All buildings and resources will reset, but you will earn Crowns and Tamgas for permanent bonuses. Do you want to proceed?',
      'confirm_migration_btn': 'YES, START MIGRATION',
      'crowns_to_gain': 'CROWNS TO EARN',
      'ancestral_tamga': 'ANCESTRAL TAMGA',
      'kut_multiplier': 'GLORY MULTIPLIER',
      'migrant_memory_title': 'MIGRANT MEMORY',
      'total_migrations': 'TOTAL MIGRATIONS',
      'tamga_count': 'TAMGA COUNT',
      'permanent_bonus': 'PERMANENT BONUS',
      'no_migrations_yet': 'No Great Migration completed yet.\nYour migration history will be saved here after your first migration.',
      'horn_of_steppe_title': 'STEPPE RAID',
      'raid_info_title': 'RAID INFO & DEFENSE STRATEGY',
      'sfx_effects': 'SOUND EFFECTS',
      'music_steppe': 'STEPPE MUSIC',
      'on': 'ON',
      'off': 'OFF',
      'notification_prefs': 'NOTIFICATION PREFERENCES',
      'storage_full_alert': 'Storage Full Alert (80%)',
      'season_change_alert': 'Season Change Alert',
      'quest_completed_alert': 'Quest Complete Alert',
      'castle_upgrade_alert': 'Yurt Upgrade Ready Alert',
      'theme_palette': 'NEO-BRUTALIST THEME PALETTE',
      'great_migration_screen_btn': 'GREAT MIGRATION SCREEN',
      'steppe_story_btn': 'STEPPE EPIC (INTRO STORY)',
      'reward_claiming': 'CLAIMING REWARD',
      'reward_please_wait': 'Claiming reward, please wait...',
      'crown_breakdown_title': 'RENOWN & CROWN BREAKDOWN',
      'reset_calculation_subtitle': 'Great Migration Reset Calculation',
      'diorama_snapshot_title': 'STEPPE DIORAMA SNAPSHOT',
      'diorama_saved_toast': 'Diorama snapshot saved to gallery!',
      'realm_selection_title': 'REALM SELECTION',
      'steppe_lore_tree_title': 'TÖRE WISDOM TREE',
      'wisdom': 'Wisdom',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'locked': 'Locked',
      'unlock': 'Unlock',
      'equipped': 'EQUIPPED',
      'equip': 'EQUIP',
      'active': 'ACTIVE',
      'inactive': 'INACTIVE',
      'hours': 'hours',
      'minutes': 'minutes',
      'seconds': 'seconds',
      'owned': 'OWNED',
      'wild': 'WILD',
      'loading_title': 'ANCIENT STEPPE MATRIX',
      'loading_subtitle': 'Activating Isometric Voxel Engine...',
      'loading_label': 'LOADING',
      'lore_tree_title': 'ORHUN BITIG STONES & LORE TREE',
      'bitig_label': 'BITIG',
      'branch_logistics': 'Logistics',
      'branch_heating': 'Heating',
      'branch_soil': 'Soil',
      'branch_casting': 'Casting',
      'node_unlocked': 'UNLOCKED',
      'trade_orders_title': 'SILK ROAD ENVOY ORDERS',
      'no_envoy_orders': 'No pending envoy orders at this time.',
      'order_delivered': 'DELIVERED',
      'deliver_order_btn': 'DELIVER ORDER',
      'realm_active': 'ACTIVE REALM',
      'select_realm_btn': 'SELECT THIS REALM',
      'realm_altay_name': 'ALTAI CELESTIAL PLATEAUS',
      'realm_altay_sub': 'Abundance of Mines, Quarries & Damascus Steel',
      'realm_altay_desc': '• Stone, Iron and Damascus Steel production doubled.\n• 30% discount on Mountain and Crater tile conquest costs.\n• Harsh winters and high Kurgan legacy synergy.',
      'realm_idil_name': 'VOLGA-URAL RIVER BASIN',
      'realm_idil_sub': 'Abundance of Fishing, Wetlands & Kumis Yurt',
      'realm_idil_desc': '• Fish, Food, Flour and Kumis production doubled.\n• 30% discount on Sea and Reed tile conquest costs.\n• +50% prosperity resonance adjacent to rivers and lakes.',
      'realm_karakum_name': 'KARAKUM & TARIM OASES',
      'realm_karakum_sub': 'Silk Road Caravans, Market Barter & Felt Abundance',
      'realm_karakum_desc': '• Caravan speed, Market barter profits and Crown yield doubled.\n• Felt and yurt production is 50% faster.\n• 25% discount on Desert and Oasis tile conquest costs.',
      'migration_confirm_title': 'CONFIRM GREAT MIGRATION?',
      'migration_confirm_body': 'Your current lands and resources will be reset; your tribe will migrate to a new era.\n\nLegacy to Earn:\n• +{0} Crowns (Renown & Glory)\n• +{1} Permanent Ancestral Tamga\n• Your buildings will turn into Ancestral Kurgans.\n\nAre you sure you want to proceed?',
      'migration_header_title': 'GREAT MIGRATION (PRESTIGE & KUT MULTIPLIER)',
      'migration_cycle_subtitle': 'Eternal Steppe Victory Cycle & Heritage Multiplier',
      'migration_legacy_header': 'PERMANENT LEGACY TO EARN IN THIS MIGRATION',
      'migration_breakdown_title': 'LEGACY & REWARD BREAKDOWN',
      'migration_oaths_title': 'SACRED OATHS (CHALLENGE MODIFIERS)',
      'migration_target_realm_title': 'TARGET EXPEDITION REALM SELECTION',
      'migration_resources_label': 'Resources',
      'migration_victories_title': 'ETERNAL REALM VICTORIES:',
      'migration_victory_bengutas': 'Orkhon Runic Steles (Cultural)',
      'migration_victory_silkroad': 'Great Silk Road Network (Logistics)',
      'migration_victory_realms': '4 Ancient Realm Dominance (Geographic)',
      'migration_oath_iron_title': 'Oath of Steel (+15% Glory)',
      'migration_oath_iron_desc': 'Iron & mine progression boost • Extra Tamga yield',
      'migration_oath_frost_title': 'Oath of Permafrost (+15% Glory)',
      'migration_oath_frost_desc': 'Resilience against harsh winter & Zud blizzards',
      'migration_realm_steppe_title': 'Great Steppe (Standard)',
      'migration_realm_steppe_desc': 'Balanced meadows, forests & mineral basins',
      'migration_realm_silk_title': 'Silk Road Oases',
      'migration_realm_silk_desc': 'Desert biomes, caravanserai & trade boost',
      'migration_realm_altay_title': 'Altay Highlands',
      'migration_realm_altay_desc': 'Tundra & geothermal baths frost challenge',
      'migration_not_ready_warning': 'Realm not ready for migration (Requires Yurt Lv. 5 & 12 Tiles)',
      'migration_not_ready_toast': 'Requires Yurt Lv. 5 and 12 Tiles for Migration.',
      'start_migration_btn': 'START GREAT MIGRATION',
      'migration_locked_btn': 'MIGRATION LOCKED',
      'realm_selected_badge': 'SELECTED',
      'fish': 'Fish',
      'kumis': 'Kumis',
      'felt': 'Felt',
      'damascus_steel': 'Damascus Steel',
      'offline_gains_title': 'STEPPE OFFLINE GAINS',
      'offline_gains_toast': 'Offline steppe gains transferred to storage.',
      'offline_gains_boosted_toast': 'With steppe blessing, 2.0x doubled offline gains transferred to storage!',
      'lore_logistics_1_title': 'Swift Horse Courier',
      'lore_logistics_1_desc': 'Expands worker transport range by +1 Hex and increases caravan speed by +25%.',
      'lore_logistics_2_title': 'Silk Road Network',
      'lore_logistics_2_desc': 'Increases caravan trade synergy by +50%.',
      'lore_logistics_3_title': 'Khaganate Postal System',
      'lore_logistics_3_desc': 'Doubles worker transport capacity across the entire map.',
      'lore_weather_1_title': 'Thick Felt Weaving',
      'lore_weather_1_desc': 'Reduces heating wood cost for frozen tiles by 30% in winter.',
      'lore_weather_2_title': 'Hearth Fire Gathering',
      'lore_weather_2_desc': 'Increases winter production multiplier of heated tiles by +40%.',
      'lore_weather_3_title': 'Zud Resilience',
      'lore_weather_3_desc': 'Halves the negative production penalty of Zud blizzards.',
      'lore_soil_1_title': 'Seasonal Pasture Migration',
      'lore_soil_1_desc': 'Doubles soil health regeneration rate on fallow meadows (2x).',
      'lore_soil_2_title': 'Blessed Seed Breeding',
      'lore_soil_2_desc': 'Increases base harvest yield on all fields and orchards by +35%.',
      'lore_soil_3_title': 'Soil Respiration Burst',
      'lore_soil_3_desc': 'Triples the respiration burst multiplier of rested soil (3x).',
      'lore_metal_1_title': 'Bellows Forge Refinement',
      'lore_metal_1_desc': 'Increases ore and iron extraction speed from mines by +30%.',
      'lore_metal_2_title': 'Damascus Steel Secret',
      'lore_metal_2_desc': 'Increases Damascus Steel foundry efficiency by +50%.',
      'lore_metal_3_title': 'Modu Chanyu Bows & Blades',
      'lore_metal_3_desc': 'Doubles global yield of all mining and crafting structures (2x).',
    },
    'es': {
      'game_title': 'Kaganato HexRush',
      'food': 'Comida',
      'wood': 'Madera',
      'flour': 'Harina',
      'plank': 'Tablón',
      'bread': 'Pan',
      'furniture': 'Muebles',
      'stone': 'Piedra',
      'iron': 'Hierro',
      'crowns': 'Gloria / Rango',
      'land': 'Tierra',
      'spring': 'Primavera',
      'summer': 'Verano',
      'autumn': 'Otoño',
      'winter': 'Invierno',
      'season_spring': 'La Primavera Ha Llegado',
      'season_summer': 'El Verano Ha Comenzado',
      'season_autumn': 'Ha Comenzado la Cosecha de Otoño',
      'season_winter': 'Ha Llegado el Frío Invierno',
      'zud_blizzard_alert': '¡ATENCIÓN: Tormenta de Zud!',
      'spring_bonus_desc': 'Los rebaños prosperan y brotan los pastos',
      'summer_bonus_desc': 'Producción de comida y trigo al máximo',
      'autumn_bonus_desc': 'Rendimiento de madera +25%, tiempo de cosecha',
      'winter_penalty_desc': 'Helada y frío: Producción de comida reducida al 50%',
      'zud_production_penalty': 'Tormenta crítica: ¡Toda la producción reducida en un 40%!',
      'year': 'Año',
      'conquer': 'Conquistar',
      'cost': 'Coste',
      'free': 'GRATIS',
      'build': 'Construir',
      'upgrade': 'Mejorar',
      'collect': 'Recoger',
      'level': 'Nivel',
      'per_sec': '/s',
      'frenzy_boost': '10x Frenesí de Estepa',
      'settings': 'Ajustes',
      'privacy_policy': 'Política de Privacidad',
      'language': 'Idioma',
      'sound': 'Sonido',
      'mute': 'Silenciar',
      'reset_game': 'Reiniciar Juego',
      'castle_title': 'Yurta del Kan',
      'castle_desc': 'El corazón de tu estepa. Desbloquea tradiciones y nuevos edificios.',
      'global_bonus': 'Bonus de Velocidad Global',
      'next_unlock': 'Próximo Desbloqueo',
      'biome_meadow': 'Prado',
      'biome_forest': 'Bosque',
      'biome_mountain': 'Montaña',
      'biome_sea': 'Mar',
      'biome_desert': 'Desierto',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Volcán',
      'biome_wetland': 'Humedal',
      'biome_celestial_crater': 'Cráter Celestial',
      'biome_celestialCrater': 'Cráter Celestial',
      'biome_kurgan_valley': 'Kurgan Ancestral',
      'biome_kurganValley': 'Kurgan Ancestral',
      'biome_crystal_chasm': 'Abismo de Cristal',
      'biome_crystalChasm': 'Abismo de Cristal',
      'corn_name': 'Campo de Trigo',
      'corn_desc': 'Produce trigo y provisiones básicas.',
      'barley_name': 'Campo de Cebada',
      'barley_desc': 'Cereal resistente al frío.',
      'pasture_name': 'Pasto de Estepa',
      'pasture_desc': 'Rebaños y caballos de estepa; alta producción de carne.',
      'orchard_name': 'Huerto de Frutas',
      'orchard_desc': 'Frutas silvestres que prosperan en verano y otoño.',
      'quarry_name': 'Cantera de Piedra',
      'quarry_desc': 'Extrae bloques de piedra para la construcción.',
      'resin_camp_name': 'Campamento de Resina',
      'resin_camp_desc': 'Madera de abedul y resina para yurtas.',
      'lumberjack_name': 'Cabaña de Leñador',
      'lumberjack_desc': 'Produce madera.',
      'windmill_name': 'Molino de Viento',
      'windmill_desc': 'Convierte Comida en Harina.',
      'sawmill_name': 'Aserradero',
      'sawmill_desc': 'Convierte Madera en Tablones.',
      'bakery_name': 'Horno de Piedra',
      'bakery_desc': 'Produce Pan.',
      'furniture_name': 'Taller de Carpintería',
      'furniture_desc': 'Produce Muebles.',
      'worker_name': 'Cabaña de Obreros',
      'worker_desc': 'Transporta recursos automáticamente.',
      'watchtower_name': 'Torre de Defensa',
      'watchtower_desc': 'Torre de arqueros con alcance de 3 hexágonos; ataca enemigos automáticamente.',
      'mine_name': 'Mina',
      'mine_desc': 'Extrae Piedra y Hierro.',
      'bridge_name': 'Puente de Madera',
      'bridge_desc': 'Permite cruzar el mar.',
      'fisherman_name': 'Pescador',
      'fisherman_desc': 'Produce comida en el agua.',
      'fisherman_hut_name': 'Cabaña de Pesca',
      'fisherman_hut_desc': 'Punto de recogida para pescadores.',
      'oasis_cistern_name': 'Cisterna de Oasis',
      'oasis_cistern_desc': 'Elimina la sequía y brinda un aura de +40%.',
      'caravanserai_name': 'Caravasar de la Ruta de la Seda',
      'caravanserai_desc': 'Comercia bienes por pan y provisiones.',
      'astrolabe_name': 'Astrolabio del Desierto',
      'astrolabe_desc': 'Mapea las estrellas del desierto.',
      'reindeer_sanctuary_name': 'Santuario de Renos',
      'reindeer_sanctuary_desc': 'Produce comida y calor resistentes al frío.',
      'geothermal_bath_name': 'Baño Geotérmico',
      'geothermal_bath_desc': 'Duplica la velocidad de los obreros.',
      'permafrost_dig_name': 'Excavación Permafrost',
      'permafrost_dig_desc': 'Extrae fósiles de mamut y mineral de hierro.',
      'steam_vent_name': 'Ventila de Vapor',
      'steam_vent_desc': 'Genera presión de vapor y piedra.',
      'obsidian_forge_name': 'Forja de Obsidiana',
      'obsidian_forge_desc': 'Forja herramientas de obsidiana y hierro.',
      'herbalist_yurt_name': 'Yurta del Herbolario',
      'herbalist_yurt_desc': 'Elabora alimentos curativos del humedal.',
      'scribe_workshop_name': 'Taller de Escribas',
      'scribe_workshop_desc': 'Elabora pergaminos antiguos y tablones.',
      'celestial_anvil_name': 'Yunque Celestial',
      'celestial_anvil_desc': 'Forja Acero Meteórico a partir de meteoritos.',
      'ancestral_totem_name': 'Tótem Ancestral',
      'ancestral_totem_desc': 'Canaliza el poder de todas las migraciones.',
      'prismatic_resonator_name': 'Resonador Prismático',
      'prismatic_resonator_desc': 'Duplica el poder de todos los santuarios sagrados.',
      'granary_vault_name': 'Bóveda de Kurgan',
      'granary_vault_desc': 'Almacén logístico que aumenta la velocidad de recolección en 3 hexágonos un +50%.',
      'kumis_yurt_name': 'Yurta de Kumis',
      'kumis_yurt_desc': 'Fermenta leche de yegua para producir kumis tradicional.',
      'felt_tent_workshop_name': 'Taller de Fieltro',
      'felt_tent_workshop_desc': 'Procesa lana en fieltro resistente para yurtas y comercio.',
      'damascus_forge_name': 'Forja de Damasco',
      'damascus_forge_desc': 'Forja acero de Damasco de alta calidad mediante capas.',
      'runic_stele_name': 'Estela Rúnica de Orjón',
      'runic_stele_desc': 'Inscribe conocimientos ancestrales y genera sabiduría para el árbol Töre.',
      'market_title': 'Bazar de la Estepa',
      'market_desc': 'Comercia bienes por piedra, hierro y gloria.',
      'trade': 'Comerciar',
      'tore_title': 'Töre y Consejo',
      'tore_desc': 'Fortalece tu reino con tradiciones ancestrales.',
      'learn_talent': 'Aprender',
      'claim_title': 'Reclamar Título',
      'warm_tile': 'Calentar (+50%)',
      'locked_castle_lvl': 'Requiere Yurta Nivel {0}',
      'logistics_capacity': 'Capacidad de Carga',
      'logistics_utilized': 'En Uso',
      'logistics_idle': 'Inactivo',
      'logistics_load': 'Carga Logística',
      'capacity': 'Capacidad',
      'in_coverage_buildings': '{0} Edificios Productivos en Rango',
      'resource_breakdown_title': 'Desglose de Producción y Consumo',
      'total_production': 'Producción Total',
      'total_consumption': 'Consumo Total',
      'net_total_label': 'Balance Neto',
      'gross_production': 'Tasa de Producción Bruta',
      'net_transported': 'Ingreso Neto Transportado',
      'logistics_bottleneck': 'Cuello de Botella Logístico',
      'uncollected_surplus_warning': 'El exceso de producción se acumula debido a la capacidad de transporte limitada. Construye Cabañas de Obreros o Bóvedas de Granero.',
      'producers_label': 'PRODUCTORES',
      'consumers_label': 'CONSUMIDORES',
      'no_active_buildings': 'No hay edificios activos produciendo o consumiendo este recurso.',
      'hexpedia_title': 'HEXPEDIA - ENCICLOPEDIA DE LA ESTEPA',
      'hexpedia_search_hint': 'Buscar mecánicas, edificios o biomas...',
      'hexpedia_stats': 'ESTADÍSTICAS Y FÓRMULAS',
      'hexpedia_step_guide': 'GUÍA PASO A PASO',
      'hexpedia_tips': 'CONSEJOS TÁCTICOS',
      'hexpedia_empty': 'No se encontraron mecánicas coincidentes.',
      'welcome_khan': 'BIENVENIDO, KAN DE LA ESTEPA',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'yes': 'Sí',
      'no': 'No',
      'close': 'Cerrar',
      'skip': 'OMITIR',
      'prev': 'ANTERIOR',
      'next': 'SIGUIENTE',
      'start_adventure': 'COMENZAR AVENTURA',
      'dawn_of_steppe': 'EL AMANECER DE LA ESTEPA',
      'great_migration_title': 'Gran Migración y Renacimiento',
      'great_migration_confirm_title': 'Confirmar Gran Migración',
      'great_migration_confirm_desc': 'Se reiniciarán todos los edificios y recursos, pero ganarás Coronas y Tamgas para bonificaciones permanentes. ¿Quieres continuar?',
      'confirm_migration_btn': 'SÍ, INICIAR MIGRACIÓN',
      'crowns_to_gain': 'CORONAS A GANAR',
      'ancestral_tamga': 'TAMGA ANCESTRAL',
      'kut_multiplier': 'MULTIPLICADOR DE GLORIA',
      'migrant_memory_title': 'MEMORIA MIGRANTE',
      'total_migrations': 'MIGRACIONES TOTALES',
      'tamga_count': 'CANTIDAD DE TAMGAS',
      'permanent_bonus': 'BONIFICACIÓN PERMANENTE',
      'no_migrations_yet': 'Aún no se ha completado ninguna Gran Migración.\nTu historial se guardará aquí tras la primera.',
      'horn_of_steppe_title': 'INCURSIÓN EN LA ESTEPA',
      'raid_info_title': 'INFORMACIÓN Y ESTRATEGIA DE DEFENSA',
      'sfx_effects': 'EFECTOS DE SONIDO',
      'music_steppe': 'MÚSICA DE LA ESTEPA',
      'on': 'ENCENDIDO',
      'off': 'APAGADO',
      'notification_prefs': 'PREFERENCIAS DE NOTIFICACIÓN',
      'storage_full_alert': 'Alerta de Almacén Lleno (80%)',
      'season_change_alert': 'Alerta de Cambio de Estación',
      'quest_completed_alert': 'Alerta de Misión Completada',
      'castle_upgrade_alert': 'Alerta de Mejora de Yurta Lista',
      'theme_palette': 'PALETA TEMÁTICA NEO-BRUTALISTA',
      'great_migration_screen_btn': 'PANTALLA DE GRAN MIGRACIÓN',
      'steppe_story_btn': 'ÉPICA DE LA ESTEPA (HISTORIA)',
      'reward_claiming': 'RECLAMANDO RECOMPENSA',
      'reward_please_wait': 'Reclamando recompensa, por favor espere...',
      'crown_breakdown_title': 'DESGROSE DE GLORIA Y CORONAS',
      'reset_calculation_subtitle': 'Cálculo de Reinicio de Migración',
      'diorama_snapshot_title': 'CAPTURA DE DIORAMA',
      'diorama_saved_toast': '¡Captura de diorama guardada en la galería!',
      'realm_selection_title': 'SELECCIÓN DE REINO',
      'steppe_lore_tree_title': 'ÁRBOL DE SABIDURÍA TÖRE',
      'wisdom': 'Sabiduría',
      'claim': 'Reclamar',
      'claimed': 'Reclamado',
      'locked': 'Bloqueado',
      'unlock': 'Desbloquear',
      'equipped': 'EQUIPADO',
      'equip': 'EQUIPAR',
      'active': 'ACTIVO',
      'inactive': 'INACTIVO',
      'hours': 'horas',
      'minutes': 'minutos',
      'seconds': 'segundos',
      'owned': 'PROPIEDAD',
      'wild': 'SALVAJE',
      'loading_title': 'MATRIZ DE LA ESTEPA',
      'loading_subtitle': 'Activando Motor Vóxel Isométrico...',
      'loading_label': 'CARGANDO',
      'lore_tree_title': 'PIEDRAS BITIG DE ORHON & ÁRBOL DE SABIDURÍA',
      'bitig_label': 'BITIG',
      'branch_logistics': 'Logística',
      'branch_heating': 'Calefacción',
      'branch_soil': 'Tierra',
      'branch_casting': 'Fundición',
      'node_unlocked': 'DESBLOQUEADO',
      'trade_orders_title': 'PEDIDOS DE EMBAJADOR DE LA RUTA DE LA SEDA',
      'no_envoy_orders': 'No hay pedidos de embajador pendientes en este momento.',
      'order_delivered': 'ENTREGADO',
      'deliver_order_btn': 'ENTREGAR PEDIDO',
      'realm_active': 'REINO ACTIVO',
      'select_realm_btn': 'SELECCIONAR ESTE REINO',
      'realm_altay_name': 'MESETAS CELESTIALES DE ALTÁI',
      'realm_altay_sub': 'Abundancia de Minas, Canteras y Acero de Damasco',
      'realm_altay_desc': '• La producción de Piedra, Hierro y Acero de Damasco se duplica.\n• 30% de descuento en el costo de conquista de Montaña y Cráter.\n• Inviernos duros y gran sinergia con el legado Kurgan.',
      'realm_idil_name': 'CUENCA DEL RÍO VOLGA-URAL',
      'realm_idil_sub': 'Abundancia de Pesca, Humedales y Yurtas de Kumis',
      'realm_idil_desc': '• La producción de Pescado, Comida, Harina y Kumis se duplica.\n• 30% de descuento en el costo de conquista de Mar y Juncales.\n• +50% de resonancia de prosperidad junto a ríos y lagos.',
      'realm_karakum_name': 'KARAKUM Y OASIS DE TARIM',
      'realm_karakum_sub': 'Caravanas de la Ruta de la Seda, Trueque y Abundancia de Fieltro',
      'realm_karakum_desc': '• La velocidad de caravanas, ganancias de trueque y Coronas se duplican.\n• La producción de fieltro y yurtas es 50% más rápida.\n• 25% de descuento en el costo de conquista de Desierto y Oasis.',
      'migration_confirm_title': '¿CONFIRMAR GRAN MIGRACIÓN?',
      'migration_confirm_body': 'Se reiniciarán tus tierras y recursos actuales; tu horda migrará a una nueva era.\n\nHerencia a ganar:\n• +{0} Coronas (Puntos de Gloria)\n• +{1} Tamga Ancestral Permanente\n• Tus edificios se convertirán en Kurganes Ancestrales.\n\n¿Estás seguro de continuar?',
      'migration_header_title': 'GRAN MIGRACIÓN (PRESTIGIO Y MULTIPLICADOR DE KUT)',
      'migration_cycle_subtitle': 'Ciclo de Victoria Eterna de la Estepa y Multiplicador de Herencia',
      'migration_legacy_header': 'HERENCIA PERMANENTE A GANAR EN ESTA MIGRACIÓN',
      'migration_breakdown_title': 'DESGLOSE DE HERENCIA Y RECOMPENSAS',
      'migration_oaths_title': 'JURAMENTOS SAGRADOS (MODIFICADORES DE DESAFÍO)',
      'migration_target_realm_title': 'SELECCIÓN DE REINO DE EXPEDICIÓN',
      'migration_resources_label': 'Recursos',
      'migration_victories_title': 'VICTORIAS DEL REINO ETERNO:',
      'migration_victory_bengutas': 'Estelas Rúnicas de Orhon (Cultural)',
      'migration_victory_silkroad': 'Red de la Gran Ruta de la Seda (Logística)',
      'migration_victory_realms': 'Dominio de los 4 Reinos Ancestrales (Geográfico)',
      'migration_oath_iron_title': 'Juramento de Acero (+15% Gloria)',
      'migration_oath_iron_desc': 'Impulso a hierro y minas • Mayor rendimiento de Tamga',
      'migration_oath_frost_title': 'Juramento de Escarcha (+15% Gloria)',
      'migration_oath_frost_desc': 'Resistencia contra inviernos duros y ventiscas Zud',
      'migration_realm_steppe_title': 'Gran Estepa (Estándar)',
      'migration_realm_steppe_desc': 'Praderas, bosques y cuencas minerales equilibradas',
      'migration_realm_silk_title': 'Oasis de la Ruta de la Seda',
      'migration_realm_silk_desc': 'Biomas desérticos, caravasares y gran comercio',
      'migration_realm_altay_title': 'Mesetas de Altái',
      'migration_realm_altay_desc': 'Tundra y aguas termales frente a la helada',
      'migration_not_ready_warning': 'Horda no lista para migrar (Requiere Yurta Nv. 5 y 12 Casillas)',
      'migration_not_ready_toast': 'Se requiere Yurta Nv. 5 y 12 Casillas para Migrar.',
      'start_migration_btn': 'INICIAR GRAN MIGRACIÓN',
      'migration_locked_btn': 'MIGRACIÓN BLOQUEADA',
      'realm_selected_badge': 'SELECCIONADO',
      'fish': 'Pescado',
      'kumis': 'Kumis',
      'felt': 'Fieltro',
      'damascus_steel': 'Acero de Damasco',
      'offline_gains_title': 'GANANCIAS FUERA DE LÍNEA DE LA ESTEPA',
      'offline_gains_toast': 'Las ganancias fuera de línea se transfirieron al almacén.',
      'offline_gains_boosted_toast': '¡Con la bendición de la estepa, se transfirieron 2.0x ganancias duplicadas al almacén!',
      'lore_logistics_1_title': 'Correo a Caballo Ágil',
      'lore_logistics_1_desc': 'Amplía el alcance de transporte de trabajadores en +1 Hex y aumenta la velocidad de caravanas en +25%.',
      'lore_logistics_2_title': 'Red de la Ruta de la Seda',
      'lore_logistics_2_desc': 'Aumenta la sinergia comercial de las caravanas en +50%.',
      'lore_logistics_3_title': 'Sistema Postal del Kaganato',
      'lore_logistics_3_desc': 'Duplica la capacidad de transporte de trabajadores en todo el mapa.',
      'lore_weather_1_title': 'Tejido de Fieltro Grueso',
      'lore_weather_1_desc': 'Reduce el costo de leña para calentar casillas congeladas en un 30% en invierno.',
      'lore_weather_2_title': 'Fuego del Hogar',
      'lore_weather_2_desc': 'Aumenta el multiplicador de producción invernal de casillas calentadas en +40%.',
      'lore_weather_3_title': 'Resistencia al Zud',
      'lore_weather_3_desc': 'Reduce a la mitad la penalización de producción negativa de las ventiscas Zud.',
      'lore_soil_1_title': 'Migración Estacional de Pastos',
      'lore_soil_1_desc': 'Duplica la velocidad de regeneración de salud del suelo en praderas en barbecho (2x).',
      'lore_soil_2_title': 'Mejora de Semillas Benditas',
      'lore_soil_2_desc': 'Aumenta el rendimiento base de cosecha en todos los campos y huertos en +35%.',
      'lore_soil_3_title': 'Explosión de Respiración del Suelo',
      'lore_soil_3_desc': 'Triplica el multiplicador de respiración de la tierra descansada (3x).',
      'lore_metal_1_title': 'Mejora de Forja con Fuelles',
      'lore_metal_1_desc': 'Aumenta la velocidad de extracción de mineral y hierro de las minas en +30%.',
      'lore_metal_2_title': 'Secreto del Acero de Damasco',
      'lore_metal_2_desc': 'Aumenta la eficiencia de la fundición de Acero de Damasco en +50%.',
      'lore_metal_3_title': 'Arcos y Espadas de Modu Chanyu',
      'lore_metal_3_desc': 'Duplica el rendimiento global de todas las estructuras mineras y artesanales (2x).',
    },
    'de': {
      'game_title': 'HexRush Khaganat',
      'food': 'Nahrung',
      'wood': 'Holz',
      'flour': 'Mehl',
      'plank': 'Bretter',
      'bread': 'Brot',
      'furniture': 'Möbel',
      'stone': 'Stein',
      'iron': 'Eisen',
      'crowns': 'Ruhm / Ehre',
      'land': 'Land',
      'spring': 'Frühling',
      'summer': 'Sommer',
      'autumn': 'Herbst',
      'winter': 'Winter',
      'season_spring': 'Der Frühling Ist Da',
      'season_summer': 'Der Sommer Hat Begonnen',
      'season_autumn': 'Die Herbsternte Hat Begonnen',
      'season_winter': 'Der Winterfrost Ist Hereingebrochen',
      'zud_blizzard_alert': 'ACHTUNG: Schwerer Zud-Schneesturm!',
      'spring_bonus_desc': 'Die Herden gedeihen, die Weiden sprießen',
      'summer_bonus_desc': 'Nahrungs- und Getreideproduktion auf dem Höhepunkt',
      'autumn_bonus_desc': 'Holz- und Bauholzertrag +25%, Erntezeit',
      'winter_penalty_desc': 'Frost und Kälte: Nahrungsproduktion um 50% verlangsamt',
      'zud_production_penalty': 'Kritischer Schneesturm: Gesamte Produktion um 40% verlangsamt!',
      'year': 'Jahr',
      'conquer': 'Erobern',
      'cost': 'Kosten',
      'free': 'KOSTENLOS',
      'build': 'Bauen',
      'upgrade': 'Aufwerten',
      'collect': 'Sammeln',
      'level': 'Stufe',
      'per_sec': '/s',
      'frenzy_boost': '10x Steppendrang',
      'settings': 'Einstellungen',
      'privacy_policy': 'Datenschutzerklärung',
      'language': 'Sprache',
      'sound': 'Ton',
      'mute': 'Stumm',
      'reset_game': 'Spiel zurücksetzen',
      'castle_title': 'Khans-Jurte',
      'castle_desc': 'Das Herz deines Steppenreiches. Schaltet Traditionen und neue Bauten frei.',
      'global_bonus': 'Globaler Geschwindigkeitsbonus',
      'next_unlock': 'Nächste Freischaltung',
      'biome_meadow': 'Wiese',
      'biome_forest': 'Wald',
      'biome_mountain': 'Berg',
      'biome_sea': 'Meer',
      'biome_desert': 'Wüste',
      'biome_tundra': 'Tundra',
      'biome_volcano': 'Vulkan',
      'biome_wetland': 'Feuchtgebiet',
      'biome_celestial_crater': 'Himmelskrater',
      'biome_celestialCrater': 'Himmelskrater',
      'biome_kurgan_valley': 'Ahnental-Kurgan',
      'biome_kurganValley': 'Ahnental-Kurgan',
      'biome_crystal_chasm': 'Kristallklamm',
      'biome_crystalChasm': 'Kristallklamm',
      'corn_name': 'Weizenfeld',
      'corn_desc': 'Produziert Weizen und Vorräte.',
      'barley_name': 'Gerstenfeld',
      'barley_desc': 'Frostresistentes Getreide für kaltes Klima.',
      'pasture_name': 'Steppenweide',
      'pasture_desc': 'Weidetiere und Steppenpferde; hohe Nahrungsproduktion.',
      'orchard_name': 'Obstgarten',
      'orchard_desc': 'Wilde Früchte mit Sommer- und Herbstschub.',
      'quarry_name': 'Steinbruch',
      'quarry_desc': 'Bricht reine Steinblöcke für den Bau.',
      'resin_camp_name': 'Harz- & Birkenhütte',
      'resin_camp_desc': 'Erntet Birkenholz und Dämmmaterial.',
      'lumberjack_name': 'Holzfällerhütte',
      'lumberjack_desc': 'Produziert Holz.',
      'windmill_name': 'Windmühle',
      'windmill_desc': 'Mahlt Nahrung zu Mehl.',
      'sawmill_name': 'Sägewerk',
      'sawmill_desc': 'Verarbeitet Holz zu Brettern.',
      'bakery_name': 'Steinofen-Bäckerei',
      'bakery_desc': 'Backt Brot.',
      'furniture_name': 'Schreinerhütte',
      'furniture_desc': 'Stellt Möbel her.',
      'worker_name': 'Arbeiterhütte',
      'worker_desc': 'Automatisiert Transport.',
      'watchtower_name': 'Wachturm',
      'watchtower_desc': 'Erhellt Nebel.',
      'mine_name': 'Mine',
      'mine_desc': 'Fördert Stein und Eisen.',
      'bridge_name': 'Holzbrücke',
      'bridge_desc': 'Überquert Wasser.',
      'fisherman_name': 'Fischer',
      'fisherman_desc': 'Produziert Nahrung auf Wasser.',
      'fisherman_hut_name': 'Fischerhütte',
      'fisherman_hut_desc': 'Sammelpunkt für Fischer.',
      'oasis_cistern_name': 'Oasenzisterne',
      'oasis_cistern_desc': 'Beseitigt Dürre und gewährt +40% Fruchtbarkeits-Aura.',
      'caravanserai_name': 'Seidenstraßen-Karawanserei',
      'caravanserai_desc': 'Tauscht Waren gegen Brot und Vorräte.',
      'astrolabe_name': 'Wüsten-Astrolabium',
      'astrolabe_desc': 'Erforscht die Wüstensterne.',
      'reindeer_sanctuary_name': 'Rentier-Jurte',
      'reindeer_sanctuary_desc': 'Produziert kälteresistente Nahrung.',
      'geothermal_bath_name': 'Thermalbad',
      'geothermal_bath_desc': 'Verdoppelt das Arbeitertempo durch Wärme.',
      'permafrost_dig_name': 'Permafrost-Bohrung',
      'permafrost_dig_desc': 'Fördert Mammutfossilien und Eisenerz.',
      'steam_vent_name': 'Dampfschlot',
      'steam_vent_desc': 'Erzeugt Dampfdruck und Stein.',
      'obsidian_forge_name': 'Obsidianschmiede',
      'obsidian_forge_desc': 'Schmiedet Obsidianwerkzeuge und Eisen.',
      'herbalist_yurt_name': 'Kräuterjurte',
      'herbalist_yurt_desc': 'Braut heilsame Nahrung aus Feuchtgebiet-Pflanzen.',
      'scribe_workshop_name': 'Schreibwerkstatt',
      'scribe_workshop_desc': 'Schöpft alte Schriftrollen und Bretter.',
      'celestial_anvil_name': 'Himmelsamboss',
      'celestial_anvil_desc': 'Schmiedet Meteoreisen aus Meteoriten.',
      'ancestral_totem_name': 'Ahnentotem',
      'ancestral_totem_desc': 'Kanalisiert das Erbe aller Wanderungen.',
      'prismatic_resonator_name': 'Kristallresonator',
      'prismatic_resonator_desc': 'Verdoppelt die Kraft aller heiligen Schreine.',
      'granary_vault_name': 'Kurgan-Gewölbe',
      'granary_vault_desc': 'Logistiklager, das das Sammeltempo im Umkreis von 3 Hexfeldern um +50% steigert.',
      'kumis_yurt_name': 'Kumis-Jurte',
      'kumis_yurt_desc': 'Fermentiert Stutenmilch zum traditionellen Steppen-Kumys.',
      'felt_tent_workshop_name': 'Filzzelt-Werkstatt',
      'felt_tent_workshop_desc': 'Verarbeitet Wolle zu strapazierfähigem Filz für Jurten und Handel.',
      'damascus_forge_name': 'Damast-Schmiede',
      'damascus_forge_desc': 'Schmiedet feinsten Damaszenerstahl in Mehrlagen-Technik.',
      'runic_stele_name': 'Orchon-Runenstele',
      'runic_stele_desc': 'Hält altes Steppenwissen fest und erzeugt Weisheit für den Töre-Baum.',
      'market_title': 'Steppenbasar',
      'market_desc': 'Tausche Waren gegen Stein, Eisen und Ruhm.',
      'trade': 'Tauschen',
      'tore_title': 'Töre & Rat',
      'tore_desc': 'Stärke dein Reich mit alten Traditionen und Titeln.',
      'learn_talent': 'Lernen',
      'claim_title': 'Titel beanspruchen',
      'warm_tile': 'Wärmen (+50%)',
      'locked_castle_lvl': 'Erfordert Jurte Stufe {0}',
      'logistics_capacity': 'Tragfähigkeit',
      'logistics_utilized': 'Genutzt',
      'logistics_idle': 'Frei',
      'logistics_load': 'Logistiklast',
      'capacity': 'Kapazität',
      'in_coverage_buildings': '{0} Produktionsbauten in Reichweite',
      'resource_breakdown_title': 'Produktions- & Verbrauchsübersicht',
      'total_production': 'Gesamtproduktion',
      'total_consumption': 'Gesamtverbrauch',
      'net_total_label': 'Nettobilanz',
      'gross_production': 'Brutto-Produktionsrate',
      'net_transported': 'Netto-Transporteinkommen',
      'logistics_bottleneck': 'Logistikengpass',
      'uncollected_surplus_warning': 'Überschüssige Produktion sammelt sich an. Bauen Sie Arbeiterhütten oder Vorratsgewölbe.',
      'producers_label': 'PRODUZENTEN',
      'consumers_label': 'VERBRAUCHER',
      'no_active_buildings': 'Keine aktiven Bauten für diesen Rohstoff.',
      'hexpedia_title': 'HEXPEDIA - STEPPEN-ENZYKLOPÄDIE',
      'hexpedia_search_hint': 'Mechaniken, Gebäude oder Biome suchen...',
      'hexpedia_stats': 'MECHANIK-DATEN & FORMELN',
      'hexpedia_step_guide': 'SCHRITT-FÜR-SCHRITT-ANLEITUNG',
      'hexpedia_tips': 'TAKTIK-TIPPS',
      'hexpedia_empty': 'Keine passenden Mechaniken gefunden.',
      'welcome_khan': 'WILLKOMMEN, KHAGAN DER STEPPE',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'yes': 'Ja',
      'no': 'Nein',
      'close': 'Schließen',
      'skip': 'ÜBERSPRINGEN',
      'prev': 'ZURÜCK',
      'next': 'WEITER',
      'start_adventure': 'ABENTEUER STARTEN',
      'dawn_of_steppe': 'DÄMMERUNG DER STEPPE',
      'great_migration_title': 'Große Migration & Reichesneuerung',
      'great_migration_confirm_title': 'Große Migration Bestätigen',
      'great_migration_confirm_desc': 'Alle Gebäude und Ressourcen werden zurückgesetzt, aber Sie verdienen Kronen und Tamgas für permanente Boni. Möchten Sie fortfahren?',
      'confirm_migration_btn': 'JA, MIGRATION STARTEN',
      'crowns_to_gain': 'ZU VERDIENENDE KRONEN',
      'ancestral_tamga': 'AHNEN-TAMGA',
      'kut_multiplier': 'RUHM-MULTIPLIKATOR',
      'migrant_memory_title': 'MIGRANTENGEDÄCHTNIS',
      'total_migrations': 'GESAMTE MIGRATIONEN',
      'tamga_count': 'TAMGA-ANZAHL',
      'permanent_bonus': 'PERMANENTER BONUS',
      'no_migrations_yet': 'Noch keine Große Migration abgeschlossen.\nIhre Historie wird hier nach der ersten gespeichert.',
      'horn_of_steppe_title': 'STEPPENÜBERFALL',
      'raid_info_title': 'ÜBERFALLINFO & VERTEIDIGUNG',
      'sfx_effects': 'SOUNDEFFEKTE',
      'music_steppe': 'STEPPENMUSIK',
      'on': 'AN',
      'off': 'AUS',
      'notification_prefs': 'BENACHRICHTIGUNGSEINSTELLUNGEN',
      'storage_full_alert': 'Lager-Voll-Warnung (80%)',
      'season_change_alert': 'Jahreszeitenwechsel-Warnung',
      'quest_completed_alert': 'Quest-Abschluss-Warnung',
      'castle_upgrade_alert': 'Jurten-Aufwertungs-Warnung',
      'theme_palette': 'NEO-BRUTALIST-THEMENPALETTE',
      'great_migration_screen_btn': 'GROSSE MIGRATION BILDSHIRM',
      'steppe_story_btn': 'STEPPEN-EPOS (INTRO-STORY)',
      'reward_claiming': 'BELOHNUNG WIRD ERHALTEN',
      'reward_please_wait': 'Belohnung wird abgerufen, bitte warten...',
      'crown_breakdown_title': 'RUHM- & KRONEN-ÜBERSICHT',
      'reset_calculation_subtitle': 'Große Migration Berechnungsübersicht',
      'diorama_snapshot_title': 'STEPPEN-DIORAMA SNAPSHOT',
      'diorama_saved_toast': 'Diorama-Foto in der Galerie gespeichert!',
      'realm_selection_title': 'REICHSAUSWAHL',
      'steppe_lore_tree_title': 'TÖRE-WEISHEITSBAUM',
      'wisdom': 'Weisheit',
      'claim': 'Beanspruchen',
      'claimed': 'Beansprucht',
      'locked': 'Gesperrt',
      'unlock': 'Freischalten',
      'equipped': 'AUSGERÜSTET',
      'equip': 'AUSRÜSTEN',
      'active': 'AKTIV',
      'inactive': 'INAKTIV',
      'hours': 'Stunden',
      'minutes': 'Minuten',
      'seconds': 'Sekunden',
      'owned': 'BESITZ',
      'wild': 'WILD',
      'loading_title': 'ANTIKE STEPPEN-MATRIX',
      'loading_subtitle': 'Isometrische Voxel-Engine wird aktiviert...',
      'loading_label': 'LÄDT',
      'lore_tree_title': 'ORHUN-BITIG-STEINE & WEISHEITSBAUM',
      'bitig_label': 'BITIG',
      'branch_logistics': 'Logistik',
      'branch_heating': 'Erwärmung',
      'branch_soil': 'Boden',
      'branch_casting': 'Gießen',
      'node_unlocked': 'FREIGESCHALTET',
      'trade_orders_title': 'SEIDENSTRASSEN-GESANDTENAUFTRÄGE',
      'no_envoy_orders': 'Derzeit keine ausstehenden Gesandtenaufträge vorhanden.',
      'order_delivered': 'GELIEFERT',
      'deliver_order_btn': 'AUFTRAG LIEFERN',
      'realm_active': 'AKTIVES REICH',
      'select_realm_btn': 'DIESES REICH WÄHLEN',
      'realm_altay_name': 'HIMMLISCHE HOCHEBENEN DES ALTAI',
      'realm_altay_sub': 'Fülle an Minen, Steinbrüchen & Damaszener Stahl',
      'realm_altay_desc': '• Stein-, Eisen- und Damaszener-Stahl-Produktion verdoppelt.\n• 30% Rabatt auf Eroberungskosten für Berg- und Kraterfelder.\n• Harte Winter und hohe Synergie mit dem Kurgan-Erbe.',
      'realm_idil_name': 'WOLGA-URAL-FLUSSFLÄCHE',
      'realm_idil_sub': 'Fülle an Fischerei, Feuchtgebieten & Kumis-Jurten',
      'realm_idil_desc': '• Fisch-, Nahrungs-, Mehl- und Kumis-Produktion verdoppelt.\n• 30% Rabatt auf Eroberungskosten für Meer- und Schilffelder.\n• +50% Wohlstandsresonanz in der Nähe von Flüssen und Seen.',
      'realm_karakum_name': 'KARAKUM & TARIM-OASEN',
      'realm_karakum_sub': 'Seidenstraßen-Karawanen, Tauschhandel & Filzfülle',
      'realm_karakum_desc': '• Karawanengeschwindigkeit, Tauschgewinne und Kronen verdoppelt.\n• Filz- und Jurtenherstellung ist 50% schneller.\n• 25% Rabatt auf Eroberungskosten für Wüsten- und Oasenfelder.',
      'migration_confirm_title': 'GROSSE MIGRATION BESTÄTIGEN?',
      'migration_confirm_body': 'Ihre aktuellen Ländereien und Ressourcen werden zurückgesetzt; Ihre Horde zieht in ein neues Zeitalter.\n\nZu verdienendes Erbe:\n• +{0} Kronen (Ruhmespunkte)\n• +{1} Permanente Ahnen-Tamga\n• Ihre Gebäude werden zu Ahnen-Kurganen.\n\nSind Sie sicher, dass Sie fortfahren möchten?',
      'migration_header_title': 'GROSSE MIGRATION (PRESTIGE & KUT-MULTIPLIKATOR)',
      'migration_cycle_subtitle': 'Ewiger Steppensieg-Zyklus & Erbe-Multiplikator',
      'migration_legacy_header': 'IN DIESER MIGRATION ZU VERDIENENDES AHNENERBE',
      'migration_breakdown_title': 'AUFSCHLÜSSELUNG DER AHNENBELOHNUNGEN',
      'migration_oaths_title': 'HEILIGE EIDE (HERAUSFORDERUNGS-MODIFIKATOREN)',
      'migration_target_realm_title': 'ZIELREICH-AUSWAHL FÜR DIE EXPEDITION',
      'migration_resources_label': 'Ressourcen',
      'migration_victories_title': 'EWIGE REICHS-SIEGE:',
      'migration_victory_bengutas': 'Orhun-Bengü-Steine (Kulturell)',
      'migration_victory_silkroad': 'Großes Seidenstraßen-Netzwerk (Logistik)',
      'migration_victory_realms': 'Beherrschung der 4 Uralten Reiche (Geografisch)',
      'migration_oath_iron_title': 'Eid des Stahls (+15% Ruhm)',
      'migration_oath_iron_desc': 'Eisen- & Minenfortschritt-Boost • Zusätzliche Tamga-Ausbeute',
      'migration_oath_frost_title': 'Eid des Dauerfrosts (+15% Ruhm)',
      'migration_oath_frost_desc': 'Widerstand gegen harten Winter & Zud-Schneestürme',
      'migration_realm_steppe_title': 'Große Steppe (Standard)',
      'migration_realm_steppe_desc': 'Ausgewogene Wiesen, Wälder & Mineralbecken',
      'migration_realm_silk_title': 'Seidenstraßen-Oasen',
      'migration_realm_silk_desc': 'Wüstenbiome, Karawansereien & hoher Handel',
      'migration_realm_altay_title': 'Altai-Hochebenen',
      'migration_realm_altay_desc': 'Tundra & Geothermalquellen trotzen dem Frost',
      'migration_not_ready_warning': 'Horde noch nicht bereit zur Migration (Erfordert Jurte St. 5 & 12 Felder)',
      'migration_not_ready_toast': 'Erfordert Kağan-Jurte St. 5 und 12 Felder für die Migration.',
      'start_migration_btn': 'GROSSE MIGRATION STARTEN',
      'migration_locked_btn': 'MIGRATION GESPERRT',
      'realm_selected_badge': 'AUSGEWÄHLT',
      'fish': 'Fisch',
      'kumis': 'Kumis',
      'felt': 'Filz',
      'damascus_steel': 'Damaszener Stahl',
      'offline_gains_title': 'STEPPEN-OFFLINE-GEWINNE',
      'offline_gains_toast': 'Offline-Steppengewinne wurden ins Lager übertragen.',
      'offline_gains_boosted_toast': 'Mit dem Steppensegen wurden 2.0x verdoppelte Offline-Gewinne ins Lager übertragen!',
      'lore_logistics_1_title': 'Flotter Reiterkurier',
      'lore_logistics_1_desc': 'Erweitert die Arbeitertransportreichweite um +1 Hex und erhöht die Karawanengeschwindigkeit um +25%.',
      'lore_logistics_2_title': 'Seidenstraßen-Netzwerk',
      'lore_logistics_2_desc': 'Erhöht die Handelssynergie der Karawanen um +50%.',
      'lore_logistics_3_title': 'Khaganat-Postsystem',
      'lore_logistics_3_desc': 'Verdoppelt die Arbeitertransportkapazität auf der gesamten Karte.',
      'lore_weather_1_title': 'Dicke Filzwebe',
      'lore_weather_1_desc': 'Reduziert die Heizholzkosten für gefrorene Felder im Winter um 30%.',
      'lore_weather_2_title': 'Herdfeuer-Versammlung',
      'lore_weather_2_desc': 'Erhöht den Winter-Produktionsmultiplikator beheizter Felder um +40%.',
      'lore_weather_3_title': 'Zud-Widerstand',
      'lore_weather_3_desc': 'Halbiert die negative Produktionsstrafe von Zud-Schneestürmen.',
      'lore_soil_1_title': 'Saisonale Weidewanderung',
      'lore_soil_1_desc': 'Verdoppelt die Regenerationsrate der Bodengesundheit auf brachliegenden Wiesen (2x).',
      'lore_soil_2_title': 'Gesegnete Saatzucht',
      'lore_soil_2_desc': 'Erhöht den Basis-Ernteertrag auf allen Feldern und Obstgärten um +35%.',
      'lore_soil_3_title': 'Bodenatmungsausbruch',
      'lore_soil_3_desc': 'Verdreifacht den Atmungsausbruchs-Multiplikator von ausgeruhtem Boden (3x).',
      'lore_metal_1_title': 'Blasebalg-Schmiedeverbesserung',
      'lore_metal_1_desc': 'Erhöht die Erz- und Eisengewinnungsgeschwindigkeit aus Minen um +30%.',
      'lore_metal_2_title': 'Damaszener Stahl Geheimnis',
      'lore_metal_2_desc': 'Erhöht die Effizienz der Damaszener-Stahl-Gießerei um +50%.',
      'lore_metal_3_title': 'Modu-Chanyu-Bögen & Klingen',
      'lore_metal_3_desc': 'Verdoppelt den globalen Ertrag aller Bergbau- und Handwerksgebäude (2x).',
    },
  };

  static String get(String key, {String lang = 'tr', List<String>? args}) {
    final map = _strings[lang] ?? _strings['tr']!;
    String result = map[key] ?? key;
    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        result = result.replaceAll('{$i}', args[i]);
      }
    }
    return result;
  }
}
