class GameLocalization {
  static const List<String> supportedLanguages = ['tr', 'en', 'es', 'de'];

  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'game_title': 'Hex Idle Krallığı',
      'food': 'Gıda',
      'wood': 'Odun',
      'flour': 'Un',
      'plank': 'Kereste',
      'bread': 'Ekmek',
      'furniture': 'Mobilya',
      'stone': 'Taş',
      'iron': 'Demir',
      'crowns': 'Taç',
      'land': 'Toprak',
      'spring': 'Bahar',
      'summer': 'Yaz',
      'autumn': 'Sonbahar',
      'winter': 'Kış',
      'year': 'Yıl',
      'conquer': 'Toprağı Fethet',
      'cost': 'Maliyet',
      'free': 'ÜCRETSİZ',
      'build': 'İnşa Et',
      'upgrade': 'Geliştir',
      'collect': 'Topla',
      'level': 'Seviye',
      'per_sec': '/sn',
      'frenzy_boost': '10x Çılgınlık',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'sound': 'Ses',
      'mute': 'Sessize Al',
      'reset_game': 'Oyunu Sıfırla',
      'castle_title': '🏰 Krallık Şatosu',
      'global_bonus': 'Küresel Hız Bonusu',
      'next_unlock': 'Sonraki Kilit Açılımı',
      'biome_meadow': 'Çayır',
      'biome_forest': 'Orman',
      'biome_mountain': 'Dağ',
      'biome_sea': 'Deniz',
      'corn_name': 'Mısır Tarlası',
      'corn_desc': 'Temel gıda üretimi yapar.',
      'lumberjack_name': 'Oduncu Kulübesi',
      'lumberjack_desc': 'Temel odun üretimi yapar.',
      'windmill_name': 'Değirmen (Tier 2)',
      'windmill_desc': 'Gıdayı Un\'a çevirir.',
      'sawmill_name': 'Kereste Fabrikası (Tier 2)',
      'sawmill_desc': 'Odunu Kalas\'a çevirir.',
      'bakery_name': 'Taş Fırın (Tier 3)',
      'bakery_desc': 'Un ve Gıdadan Ekmek üretir.',
      'furniture_name': 'Mobilyacı (Tier 3)',
      'furniture_desc': 'Kalas ve Odundan Mobilya üretir.',
      'worker_name': 'İşçi Kulübesi',
      'worker_desc': 'Otomatik hammadde taşır.',
      'watchtower_name': 'Gözcü Kulesi',
      'watchtower_desc': 'Geniş görüş alanı açar.',
      'mine_name': 'Maden Ocağı',
      'mine_desc': 'Taş ve demir çıkarır.',
      'bridge_name': 'Ahşap Köprü',
      'bridge_desc': 'Deniz geçişini sağlar.',
      'market_title': '⚖️ Krallık Pazarı',
      'market_desc': 'Ürettiğin malları ticaretle taş, demir ve taca dönüştür.',
      'trade': 'Takas Et',
      'tore_title': '📜 Töre & Unvanlar',
      'tore_desc': 'Kadim töre yetenekleri ve unvanlarla krallığını güçlendir.',
      'learn_talent': 'Öğren',
      'claim_title': 'Unvanı Al',
      'warm_tile': '🔥 Isıt (+%50 Hız)',
      'locked_castle_lvl': 'Şato Seviye {0} Gerekli',
    },
    'en': {
      'game_title': 'Hex Idle Kingdom',
      'food': 'Food',
      'wood': 'Wood',
      'flour': 'Flour',
      'plank': 'Plank',
      'bread': 'Bread',
      'furniture': 'Furniture',
      'stone': 'Stone',
      'iron': 'Iron',
      'crowns': 'Crowns',
      'land': 'Land',
      'spring': 'Spring',
      'summer': 'Summer',
      'autumn': 'Autumn',
      'winter': 'Winter',
      'year': 'Year',
      'conquer': 'Conquer Land',
      'cost': 'Cost',
      'free': 'FREE',
      'build': 'Build',
      'upgrade': 'Upgrade',
      'collect': 'Collect',
      'level': 'Level',
      'per_sec': '/s',
      'frenzy_boost': '10x Frenzy',
      'settings': 'Settings',
      'language': 'Language',
      'sound': 'Sound',
      'mute': 'Mute',
      'reset_game': 'Reset Game',
      'castle_title': '🏰 Kingdom Castle',
      'global_bonus': 'Global Speed Bonus',
      'next_unlock': 'Next Unlock',
      'biome_meadow': 'Meadow',
      'biome_forest': 'Forest',
      'biome_mountain': 'Mountain',
      'biome_sea': 'Sea',
      'corn_name': 'Corn Field',
      'corn_desc': 'Produces basic food.',
      'lumberjack_name': 'Lumberjack Hut',
      'lumberjack_desc': 'Produces basic wood.',
      'windmill_name': 'Windmill (Tier 2)',
      'windmill_desc': 'Converts Food into Flour.',
      'sawmill_name': 'Sawmill (Tier 2)',
      'sawmill_desc': 'Converts Wood into Planks.',
      'bakery_name': 'Bakery (Tier 3)',
      'bakery_desc': 'Produces Bread from Flour & Food.',
      'furniture_name': 'Furniture Maker (Tier 3)',
      'furniture_desc': 'Produces Furniture from Planks.',
      'worker_name': 'Worker Hut',
      'worker_desc': 'Automates resource collection.',
      'watchtower_name': 'Watchtower',
      'watchtower_desc': 'Reveals fog of war.',
      'mine_name': 'Mine Quarry',
      'mine_desc': 'Produces Stone and Iron.',
      'bridge_name': 'Wooden Bridge',
      'bridge_desc': 'Allows crossing water tiles.',
      'market_title': '⚖️ Kingdom Market',
      'market_desc': 'Trade goods for stone, iron, and royal crowns.',
      'trade': 'Trade',
      'tore_title': '📜 Töre & Titles',
      'tore_desc': 'Empower your realm with ancient talents and titles.',
      'learn_talent': 'Learn',
      'claim_title': 'Claim Title',
      'warm_tile': '🔥 Warm (+50% Speed)',
      'locked_castle_lvl': 'Requires Castle Lv.{0}',
    },
    'es': {
      'game_title': 'Reino Hex Idle',
      'food': 'Comida',
      'wood': 'Madera',
      'flour': 'Harina',
      'plank': 'Tablón',
      'bread': 'Pan',
      'furniture': 'Muebles',
      'stone': 'Piedra',
      'iron': 'Hierro',
      'crowns': 'Coronas',
      'land': 'Tierra',
      'spring': 'Primavera',
      'summer': 'Verano',
      'autumn': 'Otoño',
      'winter': 'Invierno',
      'year': 'Año',
      'conquer': 'Conquistar',
      'cost': 'Coste',
      'free': 'GRATIS',
      'build': 'Construir',
      'upgrade': 'Mejorar',
      'collect': 'Recoger',
      'level': 'Nivel',
      'per_sec': '/s',
      'frenzy_boost': '10x Frenesí',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'sound': 'Sonido',
      'mute': 'Silenciar',
      'reset_game': 'Reiniciar Juego',
      'castle_title': '🏰 Castillo Real',
      'global_bonus': 'Bonus de Velocidad Global',
      'next_unlock': 'Próximo Desbloqueo',
      'biome_meadow': 'Prado',
      'biome_forest': 'Bosque',
      'biome_mountain': 'Montaña',
      'biome_sea': 'Mar',
      'corn_name': 'Campo de Maíz',
      'corn_desc': 'Produce comida básica.',
      'lumberjack_name': 'Cabaña de Leñador',
      'lumberjack_desc': 'Produce madera básica.',
      'windmill_name': 'Molino (Tier 2)',
      'windmill_desc': 'Convierte Comida en Harina.',
      'sawmill_name': 'Aserradero (Tier 2)',
      'sawmill_desc': 'Convierte Madera en Tablones.',
      'bakery_name': 'Panadería (Tier 3)',
      'bakery_desc': 'Produce Pan.',
      'furniture_name': 'Mueblería (Tier 3)',
      'furniture_desc': 'Produce Muebles.',
      'worker_name': 'Cabaña de Obreros',
      'worker_desc': 'Transporta recursos automáticamente.',
      'watchtower_name': 'Torre de Guardia',
      'watchtower_desc': 'Despeja la niebla.',
      'mine_name': 'Mina',
      'mine_desc': 'Extrae Piedra y Hierro.',
      'bridge_name': 'Puente de Madera',
      'bridge_desc': 'Permite cruzar el mar.',
      'market_title': '⚖️ Mercado del Reino',
      'market_desc': 'Comercia bienes por piedra, hierro y coronas.',
      'trade': 'Comerciar',
      'tore_title': '📜 Töre y Títulos',
      'tore_desc': 'Fortalece tu reino con talentos ancestrales.',
      'learn_talent': 'Aprender',
      'claim_title': 'Reclamar Título',
      'warm_tile': '🔥 Calentar (+50%)',
      'locked_castle_lvl': 'Requiere Castillo Nivel {0}',
    },
    'de': {
      'game_title': 'Hex Idle Königreich',
      'food': 'Nahrung',
      'wood': 'Holz',
      'flour': 'Mehl',
      'plank': 'Bretter',
      'bread': 'Brot',
      'furniture': 'Möbel',
      'stone': 'Stein',
      'iron': 'Eisen',
      'crowns': 'Kronen',
      'land': 'Land',
      'spring': 'Frühling',
      'summer': 'Sommer',
      'autumn': 'Herbst',
      'winter': 'Winter',
      'year': 'Jahr',
      'conquer': 'Erobern',
      'cost': 'Kosten',
      'free': 'KOSTENLOS',
      'build': 'Bauen',
      'upgrade': 'Aufwerten',
      'collect': 'Sammeln',
      'level': 'Stufe',
      'per_sec': '/s',
      'frenzy_boost': '10x Rausch',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'sound': 'Ton',
      'mute': 'Stumm',
      'reset_game': 'Spiel zurücksetzen',
      'castle_title': '🏰 Schloss',
      'global_bonus': 'Globaler Geschwindigkeitsbonus',
      'next_unlock': 'Nächste Freischaltung',
      'biome_meadow': 'Wiese',
      'biome_forest': 'Wald',
      'biome_mountain': 'Berg',
      'biome_sea': 'Meer',
      'corn_name': 'Maisfeld',
      'corn_desc': 'Produziert Nahrung.',
      'lumberjack_name': 'Holzfällerhütte',
      'lumberjack_desc': 'Produziert Holz.',
      'windmill_name': 'Mühle (Tier 2)',
      'windmill_desc': 'Mahl Nahrung zu Mehl.',
      'sawmill_name': 'Sägewerk (Tier 2)',
      'sawmill_desc': 'Verarbeitet Holz zu Brettern.',
      'bakery_name': 'Bäckerei (Tier 3)',
      'bakery_desc': 'Backt Brot.',
      'furniture_name': 'Möbelmacher (Tier 3)',
      'furniture_desc': 'Stellt Möbel her.',
      'worker_name': 'Arbeiterhütte',
      'worker_desc': 'Automatisiert Transport.',
      'watchtower_name': 'Wachturm',
      'watchtower_desc': 'Erhellt Nebel.',
      'mine_name': 'Mine',
      'mine_desc': 'Fördert Stein und Eisen.',
      'bridge_name': 'Holzbrücke',
      'bridge_desc': 'Überquert Wasser.',
      'market_title': '⚖️ Markt des Königreichs',
      'market_desc': 'Tausche Waren gegen Stein, Eisen und Kronen.',
      'trade': 'Tauschen',
      'tore_title': '📜 Töre & Titel',
      'tore_desc': 'Stärke dein Reich mit alten Talenten und Titeln.',
      'learn_talent': 'Lernen',
      'claim_title': 'Titel beanspruchen',
      'warm_tile': '🔥 Wärmen (+50%)',
      'locked_castle_lvl': 'Erfordert Schloss Stufe {0}',
    },
  };

  static String get(String key, {String lang = 'tr', List<String>? args}) {
    final map = _strings[lang] ?? _strings['tr']!;
    String result = map[key] ?? key;
    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        result = result.replaceAll('{$i}', args[i]);
      }
    }
    return result;
  }
}
